### ISSUE TITLE
ThingsBoard source support ?

### ISSUE THREAD

**Issue by zhanglt** [emqx/kuiper#142]
How to integrate Kuiper  and ThingsBoard(https://thingsboard.io/).

**Comment by jinfahua** [comment]
1. If you use Kuiper at edge side, then Kuiper is used for analytics in edge, and the processed results are sent to ThingsBoard [through Kuiper](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/overview.md).

2. If you'd like to use Kuiper analytics in server side, that is also fine. You can use [thingsboard mqtt external node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#mqtt-node) to send data to an MQTT broker, then use Kuiper rule to analyze IoT data.

**Comment by zhanglt** [comment]
thanks！

**Comment by jinfahua** [comment]
welcome, feel free to let us know if you have any requirements.

**Comment by jinfahua** [comment]
Solution has been provided, and close the issue.
