### ISSUE TITLE
Bind for root of  REST API - return Kuiper version as well

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#163]
Currently,  localhost:9081 returns 404, need bind contents to root address. It can just return 200 with OK, no additional contents are required.

**Comment by jinfahua** [comment]
@zhanghongtong Root path of Kuiper rest-api was supported.

```
# curl localhost:9081
OK
```

**Comment by jinfahua** [comment]
An API that can return Kuiper version, can we just re-use this?

**Comment by zhanghongtong** [comment]
I think it's okay.

**Comment by jinfahua** [comment]
Done & close the issue.
