### ISSUE TITLE
messaging.go:70 msg="Failed to receive ZMQ Message, json: cannot unmarshal array into Go value of type types.MessageEnvelope

### ISSUE THREAD

**Issue by lesliechung88** [emqx/kuiper#169]
edgex 无法解析 kuiper sink 的 zmq

我采用edgex的app-function-sdk测试接收kuiper的zmq,能收到zmq消息，但不能解析，错误如下：
messaging.go:70 msg="Failed to receive ZMQ Message, json: cannot unmarshal array into Go value of type types.MessageEnvelope

请参考edgex-core-data的发到zmq消息(5563端)

**Comment by jinfahua** [comment]
Thanks for your feedback. Yes, the message sent by zmq Kuiper sink cannot be used for sending message to EdgeX Message Bus (because the message send to EdgeX should be encoded). A dedicated EdgeX sink will be soon available at coming 0.2.1 release. You can test it once it's released.

**Comment by lesliechung88** [comment]
thinks!

**Comment by jinfahua** [comment]
Now it's supported in 0.2.1, you could have a try... Refer to [this doc](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/sinks/edgex.md) for more detailed information. Feel free to let us know if having any problems.
