### ISSUE TITLE
Kuiper 0.2.1 - Cannot  get message from edgex

### ISSUE THREAD

**Issue by lesliechung88** [emqx/kuiper#179]
``edgex.yaml`` configuration as following, but cannot receive message.

**Running env：Use 0.2.1 version, and compiled to native binary, EdgeX is Fuji, and used docker-compose in Ubuntu OS. Use app-service  pipeline mqtt and zmq to pub message, but Kuiper cannot receive any message.**

default:
  protocol: tcp
  server: localhost
  port: 5570   #**What's port? EdgeX does not have this port, is ZeroMQ or MQTT port? It seems neither of both?**
  topic: events
  serviceServer: http://localhost:10080  #**What is port 10080？If it's /api/v1/valuedescriptor, it should be 48080 of edgex**
  
#Override the global configurations
application_conf: #Conf_key
  protocol: tcp
  server: localhost
  port: 5571
  topic: application

**Stream created, and no field definitions, but cannot receive any message.**
``` shell
root@ubuntu:~/kuiper/_build/kuiper-0.2.1-linux-amd64# bin/cli create stream demo'() WITH (FORMAT="JSON", TYPE="edgex")'
Connecting to 127.0.0.1:20498... 
Stream demo is created.

[1]+  Killed                  bin/cli query
root@ubuntu:~/kuiper/_build/kuiper-0.2.1-linux-amd64# bin/cli describe stream demo
Connecting to 127.0.0.1:20498... 

Fields
------------------------------------------------------

FORMAT: JSON
TYPE: edgex


root@ubuntu:~/kuiper/_build/kuiper-0.2.1-linux-amd64# bin/cli query
Connecting to 127.0.0.1:20498... 
kuiper > select * from demo;
Query was submit successfully.
kuiper > 
```

**Comment by jinfahua** [comment]
Thanks for your feedback. Both of the 2 configurations are in file ``cmd/core-data/res/configuration.toml``. We will change the default port configurations to the value that normally used in EdgeX.

```
[MessageQueue]
Protocol = 'tcp'
Host = '*'
Port = 5563
Type = 'zero'
Topic = 'events'
```

```
[Service]
...
Host = 'localhost'
Port = 48080
...
```

**Comment by lesliechung88** [comment]
@jinfahua 

The message can be retrieved, but there is a problem: the stream can only find the following format:

[{"rotationrate":2880}][{"temperature":27.56395}]
[{"humidity":95.48503}]
[{"bool":true}][{"rotationrate":4}][{"temperature":6.945715}]
[{"humidity":4.094852}]
[{"rotationrate":5819}][{"temperature":21.14119}]
[{"bool":false}]
[{"humidity":55.49818}]
[{"rotationrate":5442}][{"temperature":11.64447}]

But,the original fields of edgex events, such as devicename, id, orgin, cannot be obtained in the stream. The original format is maintained in the stream establishment. The original format is as follows:

**{"id":"9ca84f73-c9dd-45be-b494-f6e4361e5c49","device":"RotationRate-Device","origin":1584355563897550720,"readings":[{"id":"2353187f-70c5-44fe-a434-928367c5cab4","origin":1584355563885392388,"device":"RotationRate-Device","name":"RotationRate","value":"1176"}]}**

**In addition, when sinking to edgex, the same format as above is also maintained.
So that the edgex pipeline can consume zmq message from kuiper normally, just like zmq (5563) which consumes edgex-core-data**



Thank you very much!

**Comment by lesliechung88** [comment]
@jinfahua 

In addition, in an evnet, multiple readings may be encapsulated. There are two readings as follows, respectively RotationRate and Temperature:
{
	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
	"device": "RotationRate-Device",
	"origin": 1584355563897550720,
	"readings": [{
			"id": "2353187f-70c5-44fe-a434-928367c5cab4",
			"origin": 1584355563885392388,
			"device": "RotationRate-Device",
			"name": "RotationRate",
			"value": "1176"
		},
		{
			"id": "2353187f-70c5-44fe-a434-928367c5cab5",
			"origin": 1584355563885392323,
			"device": "RotationRate-Device",
			"name": "Temperature",
			"value": "30"
		}
	]
}

It is recommended to split it into streams, as shown below, so that it is convenient for business processing (such as conditional query), otherwise the query is troublesome
{
	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
	"device": "RotationRate-Device",
	"origin": 1584355563897550720,
	"readings": [{
			"id": "2353187f-70c5-44fe-a434-928367c5cab4",
			"origin": 1584355563885392388,
			"device": "RotationRate-Device",
			"name": "RotationRate",
			"value": "1176"
		}
	]
}

{
	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
	"device": "RotationRate-Device",
	"origin": 1584355563897550720,
	"readings": [
		{
			"id": "2353187f-70c5-44fe-a434-928367c5cab5",
			"origin": 1584355563885392323,
			"device": "RotationRate-Device",
			"name": "Temperature",
			"value": "30"
		}
	]
}

**Comment by jinfahua** [comment]
> @jinfahua
> 
> The message can be retrieved, but there is a problem: the stream can only find the following format:
> 
> [{"rotationrate":2880}][{"temperature":27.56395}]
> [{"humidity":95.48503}]
> [{"bool":true}][{"rotationrate":4}][{"temperature":6.945715}]
> [{"humidity":4.094852}]
> [{"rotationrate":5819}][{"temperature":21.14119}]
> [{"bool":false}]
> [{"humidity":55.49818}]
> [{"rotationrate":5442}][{"temperature":11.64447}]
> 
> But,the original fields of edgex events, such as devicename, id, orgin, cannot be obtained in the stream. The edgex event original format is maintained in the stream establishment. The original format is as follows:
> 
> ```
> {
> 	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
> 	"device": "RotationRate-Device",
> 	"origin": 1584355563897550720,
> 	"readings": [{
> 		"id": "2353187f-70c5-44fe-a434-928367c5cab4",
> 		"origin": 1584355563885392388,
> 		"device": "RotationRate-Device",
> 		"name": "RotationRate",
> 		"value": "1176"
> 	}]
> }
> ```
> 
> **In addition, when sinking to edgex, the same format as above is also maintained. So that the edgex pipeline can consume zmq message from kuiper normally, just like zmq (5563) which consumes edgex-core-data**
> 
> Thank you very much!

@lesliechung88 Thanks for your feedback... Could you please read [How to use meta function to extract additional data from EdgeX message bus?](https://github.com/emqx/kuiper/blob/master/docs/en_US/edgex/edgex_meta.md). We provided a function named ``meta`` to get these data.

**Comment by jinfahua** [comment]
> In addition, when sinking to edgex, the same format as above is also maintained.
So that the edgex pipeline can consume zmq message from kuiper normally, just like zmq (5563) which consumes edgex-core-data

You could refer to [this doc](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/sinks/edgex.md) for how to send data to EdgeX message bus - the data sent to EdgeX message bus will be encoded.

**Comment by jinfahua** [comment]
> @jinfahua
> 
> In addition, in an event, multiple readings may be encapsulated. There are two readings as follows, respectively RotationRate and Temperature:
> 
> ```
> {
> 	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
> 	"device": "RotationRate-Device",
> 	"origin": 1584355563897550720,
> 	"readings": [{
> 			"id": "2353187f-70c5-44fe-a434-928367c5cab4",
> 			"origin": 1584355563885392388,
> 			"device": "RotationRate-Device",
> 			"name": "RotationRate",
> 			"value": "1176"
> 		},
> 		{
> 			"id": "2353187f-70c5-44fe-a434-928367c5cab5",
> 			"origin": 1584355563885392323,
> 			"device": "RotationRate-Device",
> 			"name": "Temperature",
> 			"value": "30"
> 		}
> 	]
> }
> ```
> 
> **recommend to split it into streams, as shown below, so that it is convenient for business processing (such as conditional query), otherwise the query is troublesome**
> 
> ```
> {
> 	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
> 	"device": "RotationRate-Device",
> 	"origin": 1584355563897550720,
> 	"readings": [{
> 			"id": "2353187f-70c5-44fe-a434-928367c5cab4",
> 			"origin": 1584355563885392388,
> 			"device": "RotationRate-Device",
> 			"name": "RotationRate",
> 			"value": "1176"
> 		}
> 	]
> }
> ```
> 
> ```
> {
> 	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
> 	"device": "RotationRate-Device",
> 	"origin": 1584355563897550720,
> 	"readings": [
> 		{
> 			"id": "2353187f-70c5-44fe-a434-928367c5cab5",
> 			"origin": 1584355563885392323,
> 			"device": "RotationRate-Device",
> 			"name": "Temperature",
> 			"value": "30"
> 		}
> 	]
> }
> ```
In the [How to use meta function to extract additional data from EdgeX message bus? ](https://github.com/emqx/kuiper/blob/master/docs/en_US/edgex/edgex_meta.md) describes how the data models are transferred from EdgeX to Kuiper.  We discussed the design with EdgeX App Working group, if you think your design is better than current solution, feel free to open another issue, so that we could have more detailed discussion.  Thanks!

**Comment by lesliechung88** [comment]
> > @jinfahua
> > The message can be retrieved, but there is a problem: the stream can only find the following format:
> > [{"rotationrate":2880}][{"temperature":27.56395}]
> > [{"humidity":95.48503}]
> > [{"bool":true}][{"rotationrate":4}][{"temperature":6.945715}]
> > [{"humidity":4.094852}]
> > [{"rotationrate":5819}][{"temperature":21.14119}]
> > [{"bool":false}]
> > [{"humidity":55.49818}]
> > [{"rotationrate":5442}][{"temperature":11.64447}]
> > But,the original fields of edgex events, such as devicename, id, orgin, cannot be obtained in the stream. The edgex event original format is maintained in the stream establishment. The original format is as follows:
> > ```
> > {
> > 	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
> > 	"device": "RotationRate-Device",
> > 	"origin": 1584355563897550720,
> > 	"readings": [{
> > 		"id": "2353187f-70c5-44fe-a434-928367c5cab4",
> > 		"origin": 1584355563885392388,
> > 		"device": "RotationRate-Device",
> > 		"name": "RotationRate",
> > 		"value": "1176"
> > 	}]
> > }
> > ```
> > 
> > 
> > **In addition, when sinking to edgex, the same format as above is also maintained. So that the edgex pipeline can consume zmq message from kuiper normally, just like zmq (5563) which consumes edgex-core-data**
> > Thank you very much!
> 
> @lesliechung88 Thanks for your feedback... Could you please read [How to use meta function to extract additional data from EdgeX message bus?](https://github.com/emqx/kuiper/blob/master/docs/en_US/edgex/edgex_meta.md). We provided a function named `meta` to get these data.

@jinfahua 

I used your way and encountered a new problem, how to assemble the following json format,
**### readings** is followed by an array object, as shown below

```
{
	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
	"device": "RotationRate-Device",
	"origin": 1584355563897550720,
	"**### readings**": **### [**{
		"id": "2353187f-70c5-44fe-a434-928367c5cab4",
		"origin": 1584355563885392388,
		"device": "RotationRate-Device",
		"name": "RotationRate",
		"value": "1176"
	}**### ]**
}

```

**Comment by jinfahua** [comment]
> @jinfahua
> 
> I used your way and encountered a new problem, how to assemble the following json format,
> **### readings** is followed by an array object [ ], as shown below
> 
> ```
> {
> 	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
> 	"device": "RotationRate-Device",
> 	"origin": 1584355563897550720,
> 	"readings": [ {
> 		"id": "2353187f-70c5-44fe-a434-928367c5cab4",
> 		"origin": 1584355563885392388,
> 		"device": "RotationRate-Device",
> 		"name": "RotationRate",
> 		"value": "1176"
> 	} ]
> }
> ```
> 
> I need to sink this json format to edgex message bus

Now it's not supported. Could you please tell me what kind of case that you need to send the data back into EdgeX message bus with same format again?  

If we decide to support add this feature, how to handle following case? Should we generate 2 readings for it, and what's the metadata value for ``t2`` field?

```sql
SELECT temperature, temperature*1.3 as t2 FROM events
```

**Comment by lesliechung88** [comment]
> > @jinfahua
> > I used your way and encountered a new problem, how to assemble the following json format,
> > **### readings** is followed by an array object [ ], as shown below
> > ```
> > {
> > 	"id": "9ca84f73-c9dd-45be-b494-f6e4361e5c49",
> > 	"device": "RotationRate-Device",
> > 	"origin": 1584355563897550720,
> > 	"readings": [ {
> > 		"id": "2353187f-70c5-44fe-a434-928367c5cab4",
> > 		"origin": 1584355563885392388,
> > 		"device": "RotationRate-Device",
> > 		"name": "RotationRate",
> > 		"value": "1176"
> > 	} ]
> > }
> > ```
> > 
> > 
> > I need to sink this json format to edgex message bus
> 
> Now it's not supported. Could you please tell me what kind of case that you need to send the data back into EdgeX message bus with same format again?
> 
> If we decide to support add this feature, how to handle following case? Should we generate 2 readings for it, and what's the metadata value for `t2` field?
> 
> ```sql
> SELECT temperature, temperature*1.3 as t2 FROM events
> ```

@jinfahua

The scene is external data that flows into edgex through kuiper, such as:
**Edge gateway-> emq-> kuiper-> edgex**

**Comment by lesliechung88** [comment]
@jinfahua 

How is Kuiper currently implemented? Can edgex handle this sink? I think it also needs to be encapsulated into edgex event format zmq, which can be processed by edgex pipeline

```
{
       "edgex": {
         "protocol": "tcp",
         "host": "*",
         "port": 5571,
         "topic": "application",
         "contentType": "application / json"
       }
   }
```

**Comment by jinfahua** [comment]
In your scenario, where to get the metadata information for ``Events`` & ``Reading`` ?

**Comment by jinfahua** [comment]
> @jinfahua
> 
> How is Kuiper currently implemented? Can edgex handle this sink? I think it also needs to be encapsulated into edgex event format zmq, which can be processed by edgex pipeline
> 
> ```
> {
>        "edgex": {
>          "protocol": "tcp",
>          "host": "*",
>          "port": 5571,
>          "topic": "application",
>          "contentType": "application / json"
>        }
>    }
> ```

Refer to this - https://github.com/emqx/kuiper/blob/master/xstream/sinks/edgex_sink.go

**Comment by lesliechung88** [comment]
> In your scenario, where to get the metadata information for `Events` & `Reading` ?

@jinfahua 

The third-party gateway system only needs to send data to edgex according to the edgex event json protocol. It may not be part of edgex. The purpose of doing this is to take full advantage of the high throughput of EMQ and connect the third-party gateway data to edgex. Then edgex can Use the collected data to do more processing, such as collaboration, edge computing, and finally return the results to a third-party gateway through EMQ, or upload the received data directly to the cloud

**Comment by lesliechung88** [comment]
> > @jinfahua
> > How is Kuiper currently implemented? Can edgex handle this sink? I think it also needs to be encapsulated into edgex event format zmq, which can be processed by edgex pipeline
> > ```
> > {
> >        "edgex": {
> >          "protocol": "tcp",
> >          "host": "*",
> >          "port": 5571,
> >          "topic": "application",
> >          "contentType": "application / json"
> >        }
> >    }
> > ```
> 
> Refer to this - https://github.com/emqx/kuiper/blob/master/xstream/sinks/edgex_sink.go
@jinfahua 
I probably took a look at the code. Sink to edgex is a dynamic message mode. In this way, for each message, edgex needs to write the corresponding model adaptation. Currently, edgex cannot handle such messages, which increases the workload of the code. 
Recommended to agree A json format (this format is the current event), which is convenient for processing

**Comment by jinfahua** [comment]
@lesliechung88 Thanks for your feedback. We also consulted this issue with EdgeX App group, and now we are planning to design a new solution for EdgeX sink.  A new enhancement is created for tracking the issue - https://github.com/emqx/kuiper/issues/187. Let's have discussion in that issue.
