### ISSUE TITLE
Kuiper 0.2.1 : connection is shut down

### ISSUE THREAD

**Issue by lesliechung88** [emqx/kuiper#184]
**I executed the query for a while, and the kiper service  exited**

root@ubuntu:~/kuiper/_build/kuiper-0.2.1-linux-amd64# bin/cli query
Connecting to 127.0.0.1:20498... 
kuiper > SELECT  meta(id) AS id, meta(device) AS device, meta(origin) AS origin,Temperature as value,"Temperature" as attributeName from demo where meta(Temperature->device) = "Temperature-Humidity-Device" 
Query was submit successfully.
kuiper > [{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"a18c086b-26bc-4705-ad8d-2c240b8f7701","origin":1585122880077417960,"value":1.449098}]
[{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"82a7cf99-225e-48eb-8a5f-96c71aa0c986","origin":1585122882085036852,"value":-27.667}]
[{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"123be3f1-f98c-40c5-9e41-8ba3bbf55511","origin":1585122884161139359,"value":27.63591}]
[{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"74fa9df4-4777-4512-b3c4-4d3bc601fe65","origin":1585122886169591952,"value":0.1641903}]
[{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"15fee13d-26dd-45a8-859d-2e271b5fe468","origin":1585122888187838077,"value":-0.5826383}]
[{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"cf52047b-fa1e-46d4-82c0-091adfd24de9","origin":1585122890195537842,"value":-4.695649}]
[{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"9837eff7-e902-4534-ab3f-010653cecd3a","origin":1585122892211205883,"value":14.27003}]
[{"attributeName":"Temperature","device":"Temperature-Humidity-Device","id":"947cf862-6f0f-4534-9843-654ba4e2b232","origin":1585122894224099402,"value":28.29657}]
connection is shut down
kuiper > SELECT  meta(id) AS id, meta(device) AS device, meta(origin) AS origin,Temperature as value,"Temperature" as attributeName from demo where meta(Temperature->device) = "Temperature-Humidity-Device" 
**connection is shut down**

**Comment by jinfahua** [comment]
It seems that Kuiper server restarted or stop before message ``connection is shut down`` was print. If you restarted Kuiper server, then you should exit ``query`` tool, and enter the ``./cli query`` again.

**Comment by lesliechung88** [comment]
> It seems that Kuiper server restarted or stop before message `connection is shut down` was print. If you restarted Kuiper server, then you should exit `query` tool, and enter the `./cli query` again.

@jinfahua
kuiper service is permanently stopped and will not restart automatically

**Comment by jinfahua** [comment]
> kuiper service is permanently stopped and will not restart automatically

Yes, if it's stop, and you will have to start by yourself. It should be managed by outside of Kuiper by yourself.

**Comment by lesliechung88** [comment]
@jinfahua 
Stability is important. Will it cause information loss? Is there an HA or persistence scheme?

**Comment by jinfahua** [comment]
It's recommend to use KubeEdge or K3s to manage Kuiper instances, and if those scheduling infrastructure could be used for HA.

**Comment by jinfahua** [comment]
The problem cannot be reproduced, and close the issue... Feel free to re-open it if it can be found again.
