### ISSUE TITLE
Cannot use `group` in stream definition

### ISSUE THREAD

**Issue by dcmartin** [emqx/kuiper#237]
The word `group` appears to be reserved for definition of a stream, e.g.

```
ipaddr string,hostname string,arch string,date bigint,device string,group string
```

For additional information, refer to https://github.com/dcmartin/motion-ai/blob/beta/sh/kuiper4motion.sh with non-working schema using `group` on line 99.

Thanks!

**Comment by jinfahua** [comment]
Yes, currently `group` is a keyword, and cannot be used in stream definition. We're investigating how other tools handle such case, and will come up with a solution.

**Comment by dcmartin** [comment]
FWIW, leaving the schema empty (i.e. auto-generate) appears to work fine w/ `group` as one of the attribute names in the JSON payload.

**Comment by jinfahua** [comment]
But I don't think you can use SQL for the `group` field. E,g, `SELECT group FROM mystream`, the word `group` should be processed specially.

**Comment by dcmartin** [comment]
I will test that in my further explorations; is there a list of reserved words, or should I assume the SQL dialect is the population in question?

**Comment by jinfahua** [comment]
The reserved keys of Kuiper has not been summarized yet, we will do that.

**Comment by jinfahua** [comment]
It's supported and close the issue.
