### ISSUE TITLE
Value names always got converted to lower case when using EdgeX as source

### ISSUE THREAD

**Issue by novuscy** [emqx/kuiper#249]
Value names from EdgeX are always been converted to low case, is there a way to override this behavior? 

And if a value name has some special characters like @ |, it seemed that it cannot be selected in the SELECT statement, I've tried add "" or [] like normal SQL, but it's not working.

**Comment by novuscy** [comment]
BTW, I was testing using select * statement, this issue seemed only occurred with the * statement

**Comment by jinfahua** [comment]
> Value names from EdgeX are always been converted to low case, is there a way to override this behavior?

You can use alias to convert a field name to any format. For example, 

```sql
SELECT temperature AS TEmperature FROM ...
```

> 
> And if a value name has some special characters like @ |, it seemed that it cannot be selected in the SELECT statement, I've tried add "" or [] like normal SQL, but it's not working.

Now it's not supported, we will implement in future release for field names have 'some special characters like @'. Same requirement are request as in https://github.com/emqx/kuiper/issues/237.

**Comment by novuscy** [comment]
Thanks for your reply.

However, what if I just want to select all column from EdgeX using something like `select * from demo`, is there a way to preserve the case of value name in this scenario ?

**Comment by jinfahua** [comment]
So far it's not supported, and mark this as an enhancement, will be planned in future releases.

**Comment by novuscy** [comment]
For now field names can not contain special characters, but how about alias? Can I have special characters or Chinese characters as alias in the select statement?

**Comment by jinfahua** [comment]
It's not supported for alias as well, and not suggest to use with this way. 
Maybe you can use [data template feature](https://github.com/emqx/kuiper/blob/0.3.2/docs/en_US/rules/sinks/rest.md) to convert your field to your preferred names before sending to your service?

**Comment by novuscy** [comment]
> It's not supported for alias as well, and not suggest to use with this way.
> Maybe you can use [data template feature](https://github.com/emqx/kuiper/blob/0.3.2/docs/en_US/rules/sinks/rest.md) to convert your field to your preferred names before sending to your service?

Is there any document regarding the limitation of fields name? I found that fields name cannot start with number either, like '007' is also an illegal name.

**Comment by jinfahua** [comment]
> > It's not supported for alias as well, and not suggest to use with this way.
> > Maybe you can use [data template feature](https://github.com/emqx/kuiper/blob/0.3.2/docs/en_US/rules/sinks/rest.md) to convert your field to your preferred names before sending to your service?
> 
> Is there any document regarding the limitation of fields name? I found that fields name cannot start with number either, like '007' is also an illegal name.

So far no doc for it yet, we'll write one.

**Comment by jinfahua** [comment]
Done & close the issue.
