### ISSUE TITLE
Data template examples are wrong

### ISSUE THREAD

**Issue by dmocek** [emqx/kuiper#256]
All of the data template examples on this page: https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/overview.md#data-template are wrong.  None are valid JSON.  The examples all use backtick.  These examples should be copy/paste-able into a kuiper rule.  For example:
"dataTemplate": `{"content":{{json .}}}`,
should be:
"dataTemplate": "\"content\": {{json .}}\""

**Comment by ngjaying** [comment]
@dmocek Yes, the documentation is wrong to use backtick because it is not supported in JSON. Should be `"dataTemplate": "\"content\": {{json .}}"`. We will update the document. Thanks.

**Comment by dmocek** [comment]
Thanks!  Please let me know when the docs are updated.

**Comment by ngjaying** [comment]
The doc has updated so close this one

**Comment by dmocek** [comment]
Thanks for the updates.
