### ISSUE TITLE
Detect duplicate values over a lifetime

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#257]
@dmocek mentioned in the EdgeX application Slack channel.
Does kuiper have the ability to detect duplicate values over a lifetime?  Say I have a temperature sensor and I want to suppress all duplicate values.  Can it be done with a custom function?

To add to this, does kuiper support the ability to work over “forever” data…data not within a window?

**Comment by jinfahua** [comment]
Yes, it can be supported by implementing a `deduplicate` function. For example, using following SQL to deduplicate the data.

```sql
SELECT deduplicate(temperature) FROM demo 
```
Rule actions are triggered only when a NOT duplicated message are received. For example, if rule already received `2, 3`, now if received a new message with value `4`. The output of this function could have two possibilities:

1. The output could be `[2, 3, 4]`, which produce all of existed not duplicated data.
2. The output could be only `[4]`, which only produces new arrived not duplicated data.

Another is to add a 2nd parameter to let user control the output,  such as `deduplicate(temperature, true/false) `. 
- If the 2nd parameter is true, then the output is 1st option; 
- If the 2nd parameter is true, then the output is 2nd option; 

If new arrived message is `3`, rule actions will not be triggered.

------
> To add to this, does kuiper support the ability to work over “forever” data…data not within a window?

The feature requires Kuiper to support [state](https://github.com/emqx/kuiper/issues/258), and it can be implemented after the feature is supported. One potential risk is that it will probably store lots of data in state database and make the rule running slow. 

@dmocek How do you think about the design?

**Comment by dmocek** [comment]
Yes, this is what I'm looking for.

**Comment by jinfahua** [comment]
The function is supported based on window. Refer to [this link](https://github.com/emqx/kuiper/blob/master/docs/en_US/sqls/built-in_functions.md) for more detailed info.
