### ISSUE TITLE
State management support

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#258]
State support for allowing user to store data. It possibly used in below user cases.

Refer to Flink [state function document](https://ci.apache.org/projects/flink/flink-statefun-docs-release-2.0/getting-started/java_walkthrough.html) for similar use cases.

**Comment by dmocek** [comment]
Is there a ETA for stateful functions support in kuiper?

**Comment by jinfahua** [comment]
Maybe at Jun or Jul. Refer to our 2020 roadmap: https://github.com/emqx/kuiper/projects/1#card-32636391

**Comment by dmocek** [comment]
This is a very useful feature, thanks for adding it.
