### ISSUE TITLE
call function timestamp(),reported error

### ISSUE THREAD

**Issue by hexm-gzzg** [emqx/kuiper#259]
I am running kuiper 0.3.1 and reported the following error when using the timestamp function：

kuiper > select timestamp() as tp  from Sink;
Parse SQL select timestamp() as tp  from Sink; error: found "TIMESTAMP", expected expression..

**Comment by jinfahua** [comment]
Changed the function name to `tstamp()`, so the SQL should be as following.

```sql
select tstamp() as tp from Sink;
```
