### ISSUE TITLE
Not support float 32/64  from edgex

### ISSUE THREAD

**Issue by worldmaomao** [emqx/kuiper#272]
Not supoort float32/64 from edgex.
In edgex, the float32/64 data is encoded into base64 or eNotation style. 
kuiper  should decode it.

Here is some logs:
time="2020-05-20T01:56:47Z" level=warning msg="No readings are processed for the event, so ignore it." file="edgex_source.go:162" rule=rule4
time="2020-05-20T01:56:48Z" level=warning msg="fail to get value for Holding_register_float64_40100: unkown value type: float64" file="edgex_source.go:130" rule=rule4
time="2020-05-20T01:56:48Z" level=warning msg="fail to get value for Holding_register_float32_40104: unkown value type: float32" file="edgex_source.go:130" rule=rule4

**Comment by jinfahua** [comment]
It has been supported in 0.3.2. What's your Kuiper version?

**Comment by worldmaomao** [comment]
I have created request pull(https://github.com/emqx/kuiper/pull/273).
Please refer

**Comment by jinfahua** [comment]
Thanks for your PR, one comment in the PR https://github.com/emqx/kuiper/pull/273. Could you please take a look?

**Comment by jinfahua** [comment]
Done & close the issue, released in 0.4.1.
