### ISSUE TITLE
Fail to execute multi same type actions

### ISSUE THREAD

**Issue by worldmaomao** [emqx/kuiper#274]
Here is my rule config:
=======================start=======================
{
	"id":"rule1",
  "sql": "SELECT  * from events where meta(device)=\"TestModbusDevice1\" and holding_register_uint64_40109 > 30",
  "actions": [
    {
      "rest": {
        "url": "http://192.168.8.40:49986/api/v1/resource/rest21/json",       
        "method": "post",
        "bodyType": "json",
        "dataTemplate": "{\"msg\": \"21\"}",
        "sendSingle": true
      }
    },
        {
      "rest": {
        "url": "http://192.168.8.40:49986/api/v1/resource/rest22/json",       
        "method": "post",
        "bodyType": "json",
        "dataTemplate": "{\"msg\": \"22\"}",
        "sendSingle": true
      }
    },
    {
      "log":{}
    }
  ]
}
=======================end=======================

There are 2 rest actions with diffrent url in the rule. After creating rule, only the first rest action executed.
I hope that the 2 rest action are both executed.

**Comment by jinfahua** [comment]
Could you please attach your log file (log/stream.log)

**Comment by worldmaomao** [comment]
time="2020-05-20T08:59:01Z" level=debug msg="broadcast from filter to project done" file="common_func.go:17" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="project plan receive &{events map[holding_register_float32_40104:%!s(float64=50) holding_register_float64_40100:%!s(float64=50) holding_register_int16_40114:%!s(int=50) holding_register_int32_40115:%!s(int=50) holding_register_int64_40117:%!s(int=50) holding_register_uint16_40106:%!s(int=50) holding_register_uint32_40107:%!s(int=50) holding_register_uint64_40109:%!s(uint64=50)] %!s(int64=1589965141224) map[correlationid:a08c67ed-c21b-4204-ba08-86934b9d3dff created:%!s(int64=0) device:TestModbusDevice1 holding_register_float32_40104:map[created:%!s(int64=0) device:TestModbusDevice1 id:d508c36f-639c-4f29-a873-f09a84457849 modified:%!s(int64=0) origin:%!s(int64=1589965141213181576) pushed:%!s(int64=0)] holding_register_float64_40100:map[created:%!s(int64=0) device:TestModbusDevice1 id:8332c9b9-955e-4e6b-8326-42212c132841 modified:%!s(int64=0) origin:%!s(int64=1589965141212955055) pushed:%!s(int64=0)] holding_register_int16_40114:map[created:%!s(int64=0) device:TestModbusDevice1 id:18c84416-e32d-4381-8e37-3353d7ed5dfe modified:%!s(int64=0) origin:%!s(int64=1589965141214099266) pushed:%!s(int64=0)] holding_register_int32_40115:map[created:%!s(int64=0) device:TestModbusDevice1 id:7c74b086-2cc3-4434-8fa6-23b4590417ce modified:%!s(int64=0) origin:%!s(int64=1589965141214308504) pushed:%!s(int64=0)] holding_register_int64_40117:map[created:%!s(int64=0) device:TestModbusDevice1 id:eb48ec58-b0a5-4383-acff-a2d7bfb95053 modified:%!s(int64=0) origin:%!s(int64=1589965141214585854) pushed:%!s(int64=0)] holding_register_uint16_40106:map[created:%!s(int64=0) device:TestModbusDevice1 id:b5ffa022-a699-497f-b8a5-4207c2fb6a95 modified:%!s(int64=0) origin:%!s(int64=1589965141213390474) pushed:%!s(int64=0)] holding_register_uint32_40107:map[created:%!s(int64=0) device:TestModbusDevice1 id:049a9a99-bbb3-43f2-9a4d-9860c78d99cd modified:%!s(int64=0) origin:%!s(int64=1589965141213686938) pushed:%!s(int64=0)] holding_register_uint64_40109:map[created:%!s(int64=0) device:TestModbusDevice1 id:32543b20-4f01-496a-a604-27373e2a91a2 modified:%!s(int64=0) origin:%!s(int64=1589965141213953705) pushed:%!s(int64=0)] id:3241b870-acc0-48a8-9653-d8dbf8aad1cc modified:%!s(int64=0) origin:%!s(int64=1589965141214767132) pushed:%!s(int64=0)]}" file="project_operator.go:25" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="broadcasting from project" file="common_func.go:20" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="broadcast from project to sink_log done" file="common_func.go:17" rule=rule1
time="2020-05-20T08:59:01Z" level=info msg="sink result for rule rule1: [{\"holding_register_float32_40104\":50,\"holding_register_float64_40100\":50,\"holding_register_int16_40114\":50,\"holding_register_int32_40115\":50,\"holding_register_int64_40117\":50,\"holding_register_uint16_40106\":50,\"holding_register_uint32_40107\":50,\"holding_register_uint64_40109\":50}]" file="log_sink.go:16" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg=success file="sink_node.go:280" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="broadcast from project to sink_log done" file="common_func.go:17" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="receive 1 records" file="sink_node.go:234" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="rest sink receive {\"msg\": \"21\"}" file="rest_sink.go:146" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="do request: POST http://192.168.8.40:49986/api/v1/resource/rest21/json with {{\"msg\": \"21\"}}" file="rest_sink.go:207" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg="rest sink got response &{200 OK 200 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Wed, 20 May 2020 08:59:01 GMT]] 0xc000266bc0 0 [] false false map[] 0xc00035a400 <nil>}" file="rest_sink.go:212" rule=rule1
time="2020-05-20T08:59:01Z" level=debug msg=success file="sink_node.go:280" rule=rule1

**Comment by jinfahua** [comment]
Done & close the issue, the fix is included in 0.4.1.
