### ISSUE TITLE
there is something wrong with AggregateFunction count 

### ISSUE THREAD

**Issue by worldmaomao** [emqx/kuiper#294]
**Here is the data query every 10s:**
 sql:
_SELECT  * FROM events  where meta(device)="TestModbusDevice" and (Coil_150 !=null or Coil_100 != null) GROUP BY TUMBLINGWINDOW(ss, 10)_

query data:
[{"Coil_150":true},{"Coil_100":true}]
[{"Coil_150":true},{"Coil_100":true}]
[{"Coil_150":true},{"Coil_100":true}]
[{"Coil_150":true},{"Coil_100":true}]
[{"Coil_150":true},{"Coil_100":true}]
[{"Coil_150":true},{"Coil_100":true}]

Now I want to calculate the total count  for different element  in every 10s.
Here is my sql:

_SELECT  count(Coil_150) as a, count(Coil_100) as b FROM events  where meta(device)="TestModbusDevice" and (Coil_150 !=null or Coil_100 != null) GROUP BY TUMBLINGWINDOW(ss, 10)_

the actual result:
[{"a":2,"b":2}]
[{"a":2,"b":2}]
[{"a":2,"b":2}]
[{"a":2,"b":2}]
[{"a":2,"b":2}]

the expect result:
[{"a":1,"b":1}]
[{"a":1,"b":1}]
[{"a":1,"b":1}]
[{"a":1,"b":1}]
[{"a":1,"b":1}]

So it is  something wrong with my sql or it is bug ? 
my kuiper version is 0.4.1
Thank you！

**Comment by worldmaomao** [comment]
you are a super man!

**Comment by ngjaying** [comment]
> you are a super man!

Laugh. Thanks for the very clear description, it helps us to identify the problem much faster.
