### ISSUE TITLE
Optimize the kuiper-dev image to support to run rules in kuiper-dev image

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#329]
> It would be nice if the kuiper-dev container allowed running of the rules.  With the host directory mounted, I could use my IDE to write the rules and run/test them in the dev container.  When finished, I can deploy to production.

Please refer to [related discussion](https://edgexfoundry.slack.com/archives/CE48UTVQ9/p1592846094160300?thread_ts=1591901563.128800&cid=CE48UTVQ9) for more detailed info.

**Comment by ngjaying** [comment]
kuiper dev container already includes the built Kuiper in /usr/local/kuiper. The user should be able to use it to test already.

**Comment by jinfahua** [comment]
ok, so please update the plugin development tutorial doc.
