### ISSUE TITLE
Automatically streams & rules management by monitoring specific folders

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#333]
Need Kuiper to have following capabilities,

- Stream or rule files are stored at a specific folder (by default, it could be `$kuiper/data/batch/streams` or `$kuiper/data/batch/rules`, user can update the config file if a new location is required).
- Kuiper monitors the folder, and create or update with any file updates under this folder; Or delete the rule if any files are delete.

Questions,
- Any file name conventions for rule or stream file?
- Can multiple rules/streams defined in one rule or stream file?

**Comment by luogangyi** [comment]
For second question, a related problem is how to determine if rules are deleted or updated?

**Comment by jinfahua** [comment]
> For second question, a related problem is how to determine if rules are deleted or updated?

Probably we can monitor the file timestamp of MD5 of file content, if rules/stream files are not too much, then the performance is OK.

**Comment by smart33690** [comment]
Hello，I suggest one file one rule，Because when we create a rule, create a rule file。
But if implement one file multiple rules，is also compatible one file one rule。

Relationship files and rules	
- delete file ==》 delete rule
- create file ==》 create rule
- update file ==》 delete & create rule

And how to implement `rule start/stop/restart` ?

**Comment by jinfahua** [comment]
> Hello，I suggest one file one rule，Because when we create a rule, create a rule file。
> But if implement one file multiple rules，is also compatible one file one rule。
> 
> Relationship files and rules
> 
> * delete file ==》 delete rule
> * create file ==》 create rule
> * update file ==》 delete & create rule
> 
> And how to implement `rule start/stop/restart` ?

Add a field in the config file to indicate the expected command (start/stop/restart) to run?

**Comment by ngjaying** [comment]
@smart33690 @jinfahua Can we use shell script to execute the Kuiper commands (CLI or REST) instead of inventing another interface through files? 
1. The user can write all needed commands in a shell script(command script)  and upload to a specific folder
2. Another shell script will monitor that folder for changes
    - If new command script files detected, run those script files in the order of creation and then delete them

The command script can contain all supported actions of Kuiper such as create, delete etc. which will be much more flexible.

**Comment by smart33690** [comment]
> > Hello，I suggest one file one rule，Because when we create a rule, create a rule file。
> > But if implement one file multiple rules，is also compatible one file one rule。
> > Relationship files and rules
> > 
> > * delete file ==》 delete rule
> > * create file ==》 create rule
> > * update file ==》 delete & create rule
> > 
> > And how to implement `rule start/stop/restart` ?
> 
> Add a field in the config file to indicate the expected command (start/stop/restart) to run?

I think shouldn't add a field of the control rule in the rule file

For Simple,we can 

- create rule mean start rule
- delete rule mean stop rule
- update rule mean restart rule

**Comment by smart33690** [comment]
> @smart33690 @jinfahua Can we use shell script to execute the Kuiper commands (CLI or REST) instead of inventing another interface through files?
> 
> 1. The user can write all needed commands in a shell script(command script)  and upload to a specific folder
> 2. Another shell script will monitor that folder for changes
>    
>    * If new command script files detected, run those script files in the order of creation and then delete them
> 
> The command script can contain all supported actions of Kuiper such as create, delete etc. which will be much more flexible.

k8s create configMap, then put a JSON file to specific folder
kuiper should monitor json files under this folder.
Is shell scripts may be not suitable?

**Comment by jinfahua** [comment]
KubeEdge dispatchs plugins, streams and rules configurations by ConfigMap. An application is monitoring the specified configuration file, and if there are any updates with the file, then it will execute the commands in the file one by one. It's user's responsibility to make commands correct, and with right orders. User need to check Kuiper log file to make sure all of commands are run successfully.

The sample contents of configuration file is as following.

```json
{
  "commands": [
    {
      "url": "/rules",
      "description": "create rule1",
      "method": "post",
      "data":
      {
        "id": "rule1",
        "sql": "SELECT * FROM demo",
        "actions": [{"log": {}}]
      }
    },
    {
      "url": "/rules/rule1",
      "description": "stop rule1",
      "method": "post",
      "data":{}
    }
  ]
}
```

`commands` is an JSON array, and it includes a list of command that will be issued against Kuiper server, and every command has following properties,

- `url`: The address  (no need to specify the host and port) of Rest-API. This property must be specified.
- `description`: The description for the command, it's an optional setting.
- `method`: HTTP method value, it could be `post`, `get`, `delete` or `put`. This property must be specified.
- `data`: The data post to Rest API. It's an optional setting.

It would be a standalone application (`kubeedgetool`) for parsing & executing the commands. Below are configurations for this standalone application,

```yaml
server: 127.0.0.1:9080
debug: true
log: /var/logs/kuiper/kubeedge.log
```

**Comment by jinfahua** [comment]
@luogangyi @smart33690 @ngjaying @EMQmyd Please refer to previous comment for the new design, and feel free to comments.

**Comment by ngjaying** [comment]
> An application is monitoring the specified configuration file, and if there are any updates with the file,

Will it be better to create a new file for a new configuration instead of keep updating one file? And the executed files can be moved to a backup folder like ./history.
This can avoid file lock of multiple access(read/write) of the single config file  and can save a command "log" for debug and many possibilities to leverage that log in the future.

**Comment by jinfahua** [comment]
> > An application is monitoring the specified configuration file, and if there are any updates with the file,
> 
> Will it be better to create a new file for a new configuration instead of keep updating one file? And the executed files can be moved to a backup folder like ./history.
> This can avoid file lock of multiple access(read/write) of the single config file and can save a command "log" for debug and many possibilities to leverage that log in the future.

OK, updated the design comments.

**Comment by jinfahua** [comment]
Done & close the issue.
