### ISSUE TITLE
Return a JSON message for root REST API address

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#334]
Currently, the API only returns `OK`, more information with JSON format should be returned.

- Kuiper version
- Kuiper up time
- Operator system 

The impacted modules
- A unit test
- Helmchart?
- API documents
- Kuiper management UI

**Comment by jinfahua** [comment]
@ysfscream Could you please update Kuiper management UI accordingly?

**Comment by ysfscream** [comment]
@jinfahua OK, I will update it recently.
