### ISSUE TITLE
apt/yum/brew installation support

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#335]
apt/yum/brew installation support

**Comment by zhanghongtong** [comment]
NPM is nodeJS package manager, golang is not available

**Comment by zhanghongtong** [comment]
@jinfahua 
I think [this issue](https://github.com/emqx/kuiper/issues/230) needs to be resolved before making the rpm/deb installation package,  In addition, kuiper needs to support the absolute path to make the installation package

**Comment by jinfahua** [comment]
Why need to rename the file name to support the feature? @zhanghongtong

**Comment by ngjaying** [comment]
Already supported since v0.9.0, so close
