### ISSUE TITLE
Kuiper KubeEdge (MQTT) source

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#345]
The data is consumed from KubeEdge message broker (it's an MQTT broker), so it can leverage current existed MQTT source. The model file is passed through to Kuiper by KubeEdge ConfigMap.

- Add following configuration items into `mqtt_source.yaml`

  ```yaml
  # Version of KubeEdge
  kubeedgeVersion: x.x
  # JSON file that includes KubeEdge models
  kubeedgeModelFile: /kuiper/etc/model.json
  ```

  The sample model file contents is as following,

  ```json
  {
    "deviceModels": [{
      "name": "device1",
      "properties": [
        {
        "name": "temperature",
        "dataType": "int",
        "description": "device1 description",
        "accessMode": "ReadOnly",
        "defaultValue": 0,
        "maximum": 100,
        "unit": "degree celsius"
        }, 
        {
          "name": "temperature-enable",
          "dataType": "string",
          "description": "enable temperature...",
          "accessMode": "ReadWrite",
          "defaultValue": "ON"
        }
      ]
    }]
  }
  ```

- If MQTT source finds any KubeEdge configurations, then it tries to,

  1. Load model file into memory when initializing the rule for the 1st time
     - Is it necessary to monitor the file in case of any contents updates?
  2. If any data received from MQTT topic, then it tries to convert the data to corresponding data type
     - If failed to convert the data type, then print an error message and skip the field.
  3. If no data type for the field can be found, then keep the value as is.
     -  Is it necessary to print an error message in the log?

*Comments from Gangyi,*
> "name" is not unique between different device model. So if we want to get a specific type of a property, we should use model name plus property name, like device1/temperature or other way.

**<u>Question</u>**

- Is it necessary to verify the value according to the definitions in `properties`. Such as validate value against  `maximum`  property.

**Comment by luogangyi** [comment]
Good feature!
btw, "name" is not unique between different device model. So if we want to get a specific type of a property, we should use model name plus property name, like  device1/temperature or other way.

**Comment by jinfahua** [comment]
> Good feature!
> btw, "name" is not unique between different device model. So if we want to get a specific type of a property, we should use model name plus property name, like device1/temperature or other way.

OK, updated design.

**Comment by jinfahua** [comment]
Done & close the issue, a doc will be wrote for describing how to use it.
