### ISSUE TITLE
Result in JSON array instead of JSON even using sendSingle in actions.mqtt

### ISSUE THREAD

**Issue by KShih** [emqx/kuiper#356]
**My rule file**:
``` json{
  "sql": "SELECT avg(temperature) AS t_av, max(temperature) AS t_max, min(temperature) AS t_min, COUNT(*) As t_count, split_value(mqtt(topic), \"/\", 1) AS device_id FROM demo GROUP BY device_id, TUMBLINGWINDOW(ss, 10)",
  "actions": [
    {
      "mqtt": {
        "server": "ws://localhost:8083/mqtt",
        "topic": "devices/demo_001/messages/events/",
        "clientId": "demo_001",
        "sendSingle": true
      }
    }
  ]
}
```

**Expected result:**
`payload:'{"device_id":"demo_001","t_av":6.667538453021003,"t_count":1,"t_max":6.667538453021003,"t_min":6.667538453021003}'`

**Actual result:**
`payload:'[{"device_id":"demo_001","t_av":6.667538453021003,"t_count":1,"t_max":6.667538453021003,"t_min":6.667538453021003}]'`

**Comment by jinfahua** [comment]
Please try to add `dataTemplate` property as in below.

```
actions": [
    {
      "mqtt": {
        "server": "ws://localhost:8083/mqtt",
        "topic": "devices/demo_001/messages/events/",
        "clientId": "demo_001",
        "sendSingle": true,
        "dataTemplate": "{{json .}}"
      }
    }
```

**Comment by KShih** [comment]
Thanks, it works!

**Comment by jinfahua** [comment]
@KShih A more detailed doc is wrote for [how to use data template](https://github.com/emqx/kuiper/blob/develop/docs/en_US/rules/data_template.md) in Kuiper, fyi.

**Comment by KShih** [comment]
Cool! good to know. As I referred to [this doc](https://docs.emqx.io/kuiper/latest/en/rules/overview.html), there is no such detail about using `sendSingle` with `{{json .}}`
