### ISSUE TITLE
rename tools/kubeedge to tools/kubernetes

### ISSUE THREAD

**Issue by chensheng0** [emqx/kuiper#376]
Hi:

First of all, thanks for your team's work, Kuiper is excellent.

Recently I am trying to integrate Kuiper to Baetyl which is an open edge computing framework of Linux Foundation Edge that extends cloud computing, data and service seamlessly to edge devices based on kubernetes.

I want to change tools/kubeedge to tools/kubernetes in develop branch to keep this tool is vendor-independent which is in line with the spirit of open source.

The pr is https://github.com/emqx/kuiper/pull/375.

Thanks!

**Comment by jinfahua** [comment]
Great to know that Kuiper can be work with Baetyl! We are not aware of this tool has more generic value for other Edge frameworks as well. The PR was merged :-)

**Comment by chensheng0** [comment]
I saw the pr was merged, so I am gonna close this issue.

**Comment by jinfahua** [comment]
@chensheng0 Is it necessary to integrate Baetyl device model with Kuiper as we already did for EdgeX & KubeEdge? It makes user easy to use after integration. Below is the 2 urls for more information.

- [EdgeX source integration](https://github.com/emqx/kuiper/blob/master/docs/zh_CN/edgex/edgex_rule_engine_tutorial.md#kuiper-edgex-%E9%9B%86%E6%88%90)
- [KubeEdge source integration](https://github.com/emqx/kuiper/issues/345)

**Comment by chensheng0** [comment]
@jinfahua It does helps. We will flow this design and give some suggestions when needed. Thanks!
