### ISSUE TITLE
Containerized kuiper fails when started with read-only file system

### ISSUE THREAD

**Issue by bnevis-i** [emqx/kuiper#381]
```
sed: couldn't open temporary file /kuiper/etc/sedXXXXXX: Read-only file system
```

Found in: emqx/kuiper:0.4.2-alpine

**Comment by jinfahua** [comment]
@bnevis-i With the read-only file system, can Kuiper container create files during running? Currently, if user create a new streams and rules, these information must be persistent.  Also, is it allowed to **append** contents to an existed file in read-only mode?

If all these options are not allowed, where to save information that need to be persistent?

**Comment by bnevis-i** [comment]
Ideally the documentation page at https://hub.docker.com/r/emqx/kuiper will describe were to mount a writable volume into the container to handle persistent storage needs.  It is not a good idea to write to random places in the file system because the persistent data will be lost if the container is killed and recreated.

Making the root file system read-only is done with the `--read-only` flag to [docker run](https://docs.docker.com/engine/reference/commandline/run/#options) or using the `read_only: true` setting in a docker-compose.  Read-only containers are desirable because they reduce exposure to persistent attacks (such as installing malicious binaries into the container file system).

**Comment by bnevis-i** [comment]
> @bnevis-i With the read-only file system, can Kuiper container create files during running? 

It is acceptable to run a container with --tmpfs volume mounts where temporary files may be written (typically /run and /tmp).  Also writable docker volumes can be mounted to known paths where writable files need to be placed.

> Currently, if user create a new streams and rules, these information must be persistent. Also, is it allowed to **append** contents to an existed file in read-only mode?

No.

> If all these options are not allowed, where to save information that need to be persistent?

In a mounted docker volume.

> Also, could you provide us the doc for how to test in read-only mode? Thanks.

See previous reply.

**Comment by jinfahua** [comment]
@bnevis-i Thanks for your quick response, we could fix the problem by adding a writable volume.

**Comment by bnevis-i** [comment]
@jinfahua just need documentation on where to put it.

Note that it is possible to overlay a writable volume on top of a container image that has files already in it.

For example, if you have

/srv/staticdata.txt in the image and mount a volume at /srv,

docker will copy staticdata.txt into the volume.

However, the catch is that if staticdata.txt is updated in the container image, it will never again be updated in the docker volume.

This, whereever the documentation says to mount the volume must be an initially blank file path in the image.

**Comment by jinfahua** [comment]
@bnevis-i Thanks for your detailed info... So it is not necessary to update the EdgeX docker compose file?

**Comment by bnevis-i** [comment]
> @bnevis-i Thanks for your detailed info... So it is not necessary to update the EdgeX docker compose file?

Feel free to contribute the patch!  Note that the EdgeX docker-compose methodology has changed recently... they are built from fragments of yml in the "source" directory and composed into a master docker-compose via "make build"

**Comment by jinfahua** [comment]
@bnevis-i Do you have a target date for fixing this problem? Thanks.

**Comment by bnevis-i** [comment]
@jinfahua EdgeX Hanoi release will be in the November timeframe.

**Comment by jinfahua** [comment]
@bnevis-i Thanks for quick response, we'll fix it before the EdgeX Hanoi release.
