### ISSUE TITLE
Filter for every nth element

### ISSUE THREAD

**Issue by dmocek** [emqx/kuiper#396]
Does kuiper support filtering for every nth element?  I don't see a built-in function for it.  I thought maybe I could select every nth element of a group, but I don't see support for that either.  Any way to do this without having to create a custom function?

**Comment by jinfahua** [comment]
Do you mean function such as 95% percentile data? If it's true, now it's under planning. Hopefully it would be available at the end of Sep.

**Comment by dmocek** [comment]
What I want is if I have these temperature readings coming into kuiper: 75, 79, 85, 86, 91, 92 and I want to filter for every 2nd reading, only the values 79, 86, and 92 will pass through.  If I want to filter for every 3rd reading, only the values 85, ad 92 will pass through.  If I want to filter for every 6th reading, only the value 92 will pass through.  So I want to be able to specify a number (n), and only the nth value will pass through the filter.

**Comment by jinfahua** [comment]
Currently no such functions are supported, I will set the feature as enhancement.

Below could be a workaround, but it's cumbersome.
- Use `countwindow` to [trigger data](https://github.com/emqx/kuiper/blob/develop/docs/en_US/sqls/windows.md#count-window) with specified count interval.
- Use [data template](https://github.com/emqx/kuiper/blob/develop/docs/en_US/rules/data_template.md#data-traversal) in sink to filter your expected data.

**Comment by ngjaying** [comment]
We added a new function `collect()` which will return an array of the elements of the current window. Thus, you can use index to access any of the elements in that array. For example, to get the temperature of every 3rd element, the sql will be like `SELECT Collect(*)[2]->temperature AS temp FROM demo GROUP BY COUNTWINDOW(3)`  or `SELECT Collect(temperature)[2] AS temp FROM demo GROUP BY COUNTWINDOW(3)`

**Comment by dmocek** [comment]
Great!  Quick turn-around time.  Thanks.
