### ISSUE TITLE
endless loop in rest_sink.go

### ISSUE THREAD

**Issue by worldmaomao** [emqx/kuiper#404]
This a code snapshot of rest_sink.go.

![image](https://user-images.githubusercontent.com/1459780/89517020-bb7d1c80-d80b-11ea-9a7f-b30b9985860f.png)

if the result of invoking sink.Collect is always error and the property retryInterval is bigger than 0, the code will be running in the endless loop.

I suggest that add a new property  named "retryCount" which define how many times to invoke sink.Collect.

**Comment by jinfahua** [comment]
@ngjaying Has the problem been fixed?

**Comment by ngjaying** [comment]
> @ngjaying Has the problem been fixed?

No, this is not implemented yet
