### ISSUE TITLE
Rule stopped by EOF

### ISSUE THREAD

**Issue by worldmaomao** [emqx/kuiper#406]
I found some phenomenon that some rules always  be stopped by EOF. Here is some log

![image](https://user-images.githubusercontent.com/1459780/89598771-3b4cca80-d890-11ea-84d5-62bb48562275.png)

The state of rule is 'Stopped: EOF. '

**Comment by ngjaying** [comment]
@worldmaomao It is likely that your sink cache is corrupted. Can you attach the file here $kuiper/data/sink/stores.data
As a workaround now, you can delete this file and run again.

**Comment by worldmaomao** [comment]
[sink.tar.gz](https://github.com/emqx/kuiper/files/5039097/sink.tar.gz)

**Comment by ngjaying** [comment]
This cache file is malformed. We are investigating what causes the corruption.
Are you able to run now after deleting the cache?

**Comment by ZSYun** [comment]
I came across the same situation. But I install kuiper based on docker compose. So I am wondering how I can delete the cache?
