### ISSUE TITLE
CLI panics when using 'describe plugin' command

### ISSUE THREAD

**Issue by novuscy** [emqx/kuiper#413]
The cli panics when using describe plugin command

here's the panic output:

./cli describe plugin sink
Connecting to 127.0.0.1:20498... 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main.func7(0xc0002be420, 0x0, 0xc0002845e0)
        /Users/novuscy/Projects/edgex/kuiper/xstream/cli/main.go:319 +0x371
github.com/urfave/cli.HandleAction(0x140fcc0, 0xc0002841e0, 0xc0002be420, 0xc0002be420, 0x0)
        /Users/novuscy/Projects/go/pkg/mod/github.com/urfave/cli@v1.22.0/app.go:523 +0x11a
github.com/urfave/cli.Command.Run(0x1498df1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14ab6a3, 0x29, 0x0, ...)
        /Users/novuscy/Projects/go/pkg/mod/github.com/urfave/cli@v1.22.0/command.go:174 +0x56e
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0002941c0, 0xc0002be160, 0x0, 0x0)
        /Users/novuscy/Projects/go/pkg/mod/github.com/urfave/cli@v1.22.0/app.go:404 +0x8fc
github.com/urfave/cli.Command.startApp(0x149a703, 0x8, 0x0, 0x0, 0xc000284280, 0x1, 0x1, 0x14b304f, 0x63, 0x0, ...)
        /Users/novuscy/Projects/go/pkg/mod/github.com/urfave/cli@v1.22.0/command.go:329 +0x845
github.com/urfave/cli.Command.Run(0x149a703, 0x8, 0x0, 0x0, 0xc000284280, 0x1, 0x1, 0x14b304f, 0x63, 0x0, ...)
        /Users/novuscy/Projects/go/pkg/mod/github.com/urfave/cli@v1.22.0/command.go:102 +0xa1f
github.com/urfave/cli.(*App).Run(0xc000294000, 0xc000138000, 0x4, 0x4, 0x0, 0x0)
        /Users/novuscy/Projects/go/pkg/mod/github.com/urfave/cli@v1.22.0/app.go:276 +0x7ae
main.main()
        /Users/novuscy/Projects/edgex/kuiper/xstream/cli/main.go:597 +0x1785

**Comment by jinfahua** [comment]
@novuscy Please specify the plugin name in the command line, it should be similar as following.
```
./cli describe plugin sink myplugin
```
But what you reported is a problem, we will add argument number check in the `cli` tool. Thanks.

**Comment by jinfahua** [comment]
Fixed and close the issue.
