### ISSUE TITLE
Actions falsely triggered when using EdgeX as source

### ISSUE THREAD

**Issue by novuscy** [emqx/kuiper#417]
Here's the stream I created:
```
create stream edgex_stream () WITH ( FORMAT="JSON", TYPE="edgex");
```

and here's the rule:
```
{
  "sql": "SELECT baseinfo FROM edgex_stream",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://localhost:1883",
        "topic": "rules_test"
      }
    },
    {
      "log":{}
    }
  ]
}
```

the action should only be trigger when an EdgeX event arrived which has a reading whose name is `baseinfo`, but in kuiper 0.9.0, when an EdgeX event with different reading name arrived, an empty message `[{}]` got published to the MQTT broker, here's the log:
```
time="2020-08-12T16:28:10+08:00" level=info msg="sink result for rule rule2: [{}]" file="entry.go:314" rule=rule2
```

and the message from EdgeX zeromq bus 
```
{"correlation-id":"91099b55-f4f1-4021-a7d5-36f066ae0fed","id":"ae7f7852-2072-4cf2-b4e1-db17a92ede59","device":"Test001","created":1597220890943,"origin":1597220890942926000,"readings":[{"id":"db361145-0726-4a64-a2d0-c3eddb34d56b","origin":1597220890942748000,"device":"Test001","name":"speed","value":"0","valueType":"Int16"}]}
```

IMHO, the action shouldn't be triggered at all, or did I use the SELECT statement in a wrong way?

**Comment by jinfahua** [comment]
It will produce an empty result if the specified field cannot be found in the input stream. You can have two options to solve the problem,
- Configure `omitIfEmpty` to `true` in your `mqtt` or `log` sink - refer to (detail description)[https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/overview.md#sinksactions].
- Add a WHERE condition. E,g, `WHERE baseinfo != nil`

**Comment by novuscy** [comment]
Thanks a lot, I'll try those two approaches.
