### ISSUE TITLE
kuiper kubernetes tool 

### ISSUE THREAD

**Issue by chensheng0** [emqx/kuiper#422]
Hi:

Thanks for your guys work.

We are using kuiper kubernetes tool, but we found there are only linux/amd64 arch supported.

![image](https://user-images.githubusercontent.com/49777677/90472636-8e0d6880-e153-11ea-8952-bd42aa477982.png)

Can your guys support multi-platforms ?

Thanks.

**Comment by jinfahua** [comment]
Sure, we will add other platform support in next release... It will be released at next month.

**Comment by chensheng0** [comment]
Thanks.

Right now we already built the image by ourselves.

**Comment by jinfahua** [comment]
Cool!
