### ISSUE TITLE
Add support for update rules

### ISSUE THREAD

**Issue by dmocek** [emqx/kuiper#428]
Issue #333 mentions the ability to update a rule using a file.  There should also be a way to update a rule via the REST API.  An update will stop the existing rule, install and start the updated one, and processing of the data will pause until the new rule is in effect, or the old rule is continued to be used due to an error with the update with the new rule.

**Comment by ngjaying** [comment]
This was supported since v1.0.2 so closed. Check [update rule](https://github.com/emqx/kuiper/blob/master/docs/en_US/restapi/rules.md#update-a-rule).
