### ISSUE TITLE
Documentation needs more information

### ISSUE THREAD

**Issue by dmocek** [emqx/kuiper#468]
This page https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/sinks/edgex.md states that after processing, Kuiper will send the data to the EdgeX message bus: "Publish result to EdgeX message bus without keeping original metadata" and "3. The data sent to EdgeX message bus." and "Publish result to EdgeX message bus with keeping original metadata".

However, this is not how Kuiper works. Kuiper runs it's own ZeroMQ message bus and it publishes data to it's own ZeroMQ message bus after it processes data from EdgeX. Anyone writing a service to get data after Kuiper has processed it will need to get it from Kuiper's ZeroMQ. This should be made more clear in the documentation.

I've created this EdgeX documentation issue: https://github.com/edgexfoundry/edgex-docs/issues/225

**Comment by jinfahua** [comment]
Doc was updated and it will be included in 1.0.0 version.

**Comment by jinfahua** [comment]
Close the issue.
