### ISSUE TITLE
error: cannot get the plugin file name: invalid name collect: not exist.

### ISSUE THREAD

**Issue by clh-cod** [emqx/kuiper#563]
I used the docker image: Emqx/Kuiper :0.5.1-alpine, and while testing the aggregation function,

SELECT collect(uid) as r1 FROM demo GROUP BY TumblingWindow(ss, 10);

The API error:
Parse SQL SELECT collect(uid) as r1 FROM demo GROUP BY TumblingWindow(ss, 10) error: cannot get the plugin file name: invalid name collect: not exist.

Is it because some functions are not open source?

**Comment by jinfahua** [comment]
`collect` function was supported at [0.9.1](https://github.com/emqx/kuiper/releases/tag/0.9.1), so please download the 0.9.1 version and try again.

**Comment by clh-cod** [comment]
Hello,When I deploy Emqx/Kuiper :0.9.1-alpine
The source is set with the environment variable MQTT_BROKER_ADDRESS, but the variable is valid
![image](https://user-images.githubusercontent.com/69289383/96403854-f0deb700-120b-11eb-92a4-3736cbf81e6a.png)
This is the configuration file in the container
![image](https://user-images.githubusercontent.com/69289383/96403879-048a1d80-120c-11eb-98d1-e6a3cd6acd1c.png)

**Comment by jinfahua** [comment]
It's a doc issue, and document will be fixed in the next release. Please user docker environment variable `MQTT_SOURCE__DEFAULT__SERVERS` instead of `MQTT_BROKER_ADDRESS`.

**Comment by clh-cod** [comment]
What about the environment variables MQTT_BROKER_USERNAME and MQTT_BROKER_PASSWORD?

**Comment by jinfahua** [comment]
`MQTT_SOURCE__DEFAULT__USERNAME` & `MQTT_SOURCE__DEFAULT__PASSWORD`. For more detailed, refer to [this doc](https://github.com/emqx/kuiper/blob/dev/1.0.0/deploy/docker/README.md#configuration).  

Also, refer to this link for a sample - https://github.com/emqx/kuiper/issues/394#issuecomment-693789980.

**Comment by clh-cod** [comment]
Create rule error:
Stopped: read properties map[] fail with error: json: cannot unmarshal string into Go struct field MQTTConfig.servers of type []string.

**Comment by jinfahua** [comment]
`-e MQTT_SOURCE__DEFAULT__SERVERS=[tcp://broker.emqx.io:1883]`,  MQTT server configuration is an array.

**Comment by clh-cod** [comment]
Thanks a lot !

**Comment by jinfahua** [comment]
Done & close the issue.
