### ISSUE TITLE
The status of the rule is Stopped

### ISSUE THREAD

**Issue by zhu-zyq** [emqx/kuiper#596]
1、create stream
```shell
curl -X POST \
  http://192.168.0.120:9081/streams \
  -H 'Content-Type: application/json' \
  -d '{"sql": "create stream demo() WITH (FORMAT=\"JSON\", TYPE=\"edgex\")"}'
```

2、create rule
```shell
curl -X POST \
  http://192.168.0.120:9081/rules \
  -H 'Content-Type: application/json' \
  -d '{
  "id": "rule1",
  "sql": "SELECT uint8 FROM demo WHERE uint8 > 20",
  "actions": [
    {
      "rest": {
        "url": "http://localhost:48082/api/v1/device/7d80374d-cb55-4cab-ab68-358d2b9d1538/command/a02b8dbb-61cf-4e5d-9fae-2838105a24ff",
        "method": "put",
        "dataTemplate": "{\"Bool\":\"true\", \"EnableRandomization_Bool\": \"true\"}",
        "sendSingle": true
      }
    },
    {
      "log":{}
    }
  ]
}'
```

3、show rule status
Connecting to 127.0.0.1:20498... 
```json
[
  {
    "id": "rule1",
    "status": "Stopped: cannot get the plugin file path: invalid name edgex: not exist."
  }
]
```

Question：
When creating a stream,TYPE=\"edgex\"，What is the meaning of “TYPE” ，and “ cannot get the plugin file path: invalid name edgex: not exist”，the “edgex” is the file “edgex.yaml” in etc/source?? this file is exists.

**Comment by jinfahua** [comment]
Could you please refer to this link - https://github.com/emqx/kuiper/issues/569? It can be solved by compile a native build with edgex support.

**Comment by zhu-zyq** [comment]
I was build kuiper with "make build_with_edgex",so Kuiper should support EdgeX. Kuiper's plugins/source folder is empty.

**Comment by jinfahua** [comment]
The edgex will not compiled into the `kuiperd` binary file, it will not be a separated so file in plugins/source folder. From your log, it shows that the `edgex` has not been compiled into `kuiperd` binary file.

**Comment by zhu-zyq** [comment]
Shouldn't Kuiper be compiled into edgex enabled binaries?
How can I check whether edgex is compiled into kuiperd binary?

_build/log/ stream.log file shows "Listen error: listen tcp :20498: bind: address already in use" file="server.go:72"
Thank you very much.

**Comment by jinfahua** [comment]
> Shouldn't Kuiper be compiled into edgex enabled binaries?
> How can I check whether edgex is compiled into kuiperd binary?
> 
The separated binary version of Kuiper does not include EdgeX source because EdgeX requires additional libraries (zeromq library), and Kuiper cannot be started without installing the lib. Kuiper is not only for EdgeX, so it will confuse user that do not use EdgeX. 

> build kuiper with "make build_with_edgex" ,return "Build successfully"
> _build/log/ stream.log file shows "Listen error: listen tcp :20498: bind: address already in use" file="server.go:72"
> Thank you very much.

It seems there already have an existed kuiperd process, you need to kill it.

**Comment by zhu-zyq** [comment]
Thank you very much for your patient answers . I understand what you mean. But I think it’s not a compilation problem .  Because I ran the source code of edgex-go, installed zeromq, and compiled and ran successfully. The readme file under kuiper is written to be compiled with "make build_with_edgex", which means that this version of kuiper contains the source of Edgex.  
When I get data from the EdgeX Message bus(MQTT server) when creating a stream, the rule state is running.
