### ISSUE TITLE
Shared subscription support for MQTT source

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#601]
Refer to link https://docs.emqx.net/enterprise/latest/cn/advanced/shared-subscriptions.html for shared sub.

**Comment by ngjaying** [comment]
It is supported by setting the correct topic name. 

```SQL
CREATE STREAM commandStream (cmd string, base64_img string) WITH (DATASOURCE="$queue/commands", FORMAT="JSON")
```
