### ISSUE TITLE
Kuiper manager docker images v1.0.0 and 1.0.1 are not working

### ISSUE THREAD

**Issue by untilbit** [emqx/kuiper#606]
The web interface of the kuiper manager is not loading in v1.0.0 and v1.0.1 of the docker images. It says page not found.

> sudo docker run --name kuiperManager -d -p 9082:9082 emqx/kuiper-manager:1.0.1

Docker logs don't show any errors.

**Comment by jinfahua** [comment]
@ysfscream Could you please take a look at the problem?

**Comment by jinfahua** [comment]
@zhanghongtong Could you please repack the `kuiper-manager:1.0.1`? Thanks.

**Comment by untilbit** [comment]
Any update?

@jinfahua  @zhanghongtong  @ysfscream

**Comment by ysfscream** [comment]
@untilbit Hello, sorry for the late reply. This is a bug that has been fixed, please re-pull the docker image and run it, thanks for your feedback.

**Comment by untilbit** [comment]
Issue fixed.
