### ISSUE TITLE
[1.0.1] No way to limit client and REST APIs to localhost

### ISSUE THREAD

**Issue by tonyespy** [emqx/kuiper#614]
For the Hanoi (1.3.0) release of EdgeX, we include Kuiper 1.0.1 in the edgexfoundry snap package published in the Snap Store.

While testing I noticed that the REST API is logged as listening to the address "0.0.0.0:

> Serving kuiper (version - 1.0.1) on port 20498, and restful api on http://0.0.0.0:9081

I checked the source code and sure enough the http.Server created for the REST api and the http.Server for the client both specify Addr with host hard-coded to "0.0.0.0", which means "listen on all network interfaces". Ideally this would be a configuration choice, so for instance Kuiper could be restricted to only listen on localhost for one or both.

We actually ran into a similar [issue](https://github.com/edgexfoundry/edgex-go/issues/2611) with the Geneva release of EdgeX.

Ideally it would be nice if Kuiper supported configuration settings for both REST and client servers as this would allow it to be locked down to localhost.

**Comment by tonyespy** [comment]
@EMQmyd why did you close this, do you not consider it a bug?

**Comment by rsdmike** [comment]
Hey Ya'll, we'll add this to agenda for App WG Call on 12/10. Thanks!

**Comment by jinfahua** [comment]
@tonyespy The problem was fixed, and it will be included in 1.0.2 version, which will be released at Dec, 18. 
@EMQmyd Could you please add additional description when closing the issue? Thanks.
