### ISSUE TITLE
[Kuiper Manager] Rule sql fiel is not editable

### ISSUE THREAD

**Issue by untilbit** [emqx/kuiper#624]
In kuiper manager 1.0.1 docker image the sql field is not editable.

![image](https://user-images.githubusercontent.com/12769948/100094596-8e578700-2e59-11eb-9aec-024b2c64d915.png)

**Comment by jinfahua** [comment]
@ysfscream Could you please take a look at the issue? Thanks.

**Comment by ysfscream** [comment]
@untilbit Sorry, I can’t reproduce this. issue, please refresh the page again and check the browser console for error messages.

**Comment by ngjaying** [comment]
Close as it is not reproducable. Please reopen it if you still have the problem in the newer version.
