### ISSUE TITLE
Add a ping api for keep-alive detection

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#626]
Add a `/ping` rest api for keep-alive detection.

**Comment by jinfahua** [comment]
@EMQmyd Please refer to [this link](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-command/1.2.0#/default/get_v1_ping) for more detailed information.

**Comment by EMQmyd** [comment]
1.0.3 version already supported
