### ISSUE TITLE
Binary type support

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#641]
# Kuiper Binary Support

## `bytea` type

Datatype `bytea` is a sequence of bytes, aka. byte array. The impelmentation is `[]byte` in golang.

- Literal support: 'abc \153\154\155 \052\251\124'
- Type conversion with string: [convert byte array and string](https://stackoverflow.com/questions/8009222/conversion-of-strings-containing-non-printable-characters)

### `binary` format

Add new format `binary` in stream definition:

```sql
create stream demo(image bytea) with (FORMAT="binary", source="images/")
```

Validate for this format:

1. Only one column and the column type must be bytea.
2. For schemaless mode, the column name will default to `self`.

### Soure node decode binary format

Each source needs to check format type and do decoding accordingly.

- MqttSource
- EdgeXSource
- **And a lot more...**

### Soure node decode json format with binary field

- [ ] Need to verify if binary field can be successfully decoded by json marshal.

## Image Processing Function

Validates the argument `col`'s type, must be bytea

| Function | Example                                        | Description                                   |
| -------- | ---------------------------------------------- | --------------------------------------------- |
| resize   | resize(col:bytea, width:bigint, height:bigint) | Resize the image to width * height            |
| compress | compress(col:bytea, format:string)             | Convert and compress the image to other types |

## Sink

- ImageSink: save the image fields to file.
- RestSink: add support for image upload.

**Comment by jinfahua** [comment]
# 图像目标（Sink）

目标（Sink）用于将图片保存到指定文件夹中。

## 编译和部署插件

```shell
# cd $kuiper_src
# go build --buildmode=plugin -o plugins/sinks/Image.so plugins/sinks/image.go
# cp plugins/sinks/Image.so $kuiper_install/plugins/sinks
```

重新启动 Kuiper 服务器以激活插件。

## 属性

| 属性名称 | 是否可选 | 说明                                                         |
| -------- | -------- | ------------------------------------------------------------ |
| path     | 否       | 保存结果的文件夹路径，例如  `/tmp`                           |
| interval | 是       | 接收图片的时间间隔（毫秒）。 默认值为1000，这表示每隔一秒钟接收一次图片并保存。 |
| maxAge   | 否       | 最长文件存储时间(小时)。默认值为72，这表示图片最多保存3天。  |

## 使用示例

下面示例演示了每5秒接收一次图片并将图片保存到文件夹 `/tmp`  中，同时将保存时长超过72小时的图片删除。

```json
{
  "sql": "SELECT * from demo",
  "actions": [
    {
      "image": {
        "path": "/tmp",
        "interval": 5000,
        "maxAge":72
      }
    }
  ]
}
```

**Comment by EMQmyd** [comment]
下面示例演示接收图片并将图片保存到文件夹 `/tmp`  中，同时将保存时长超过72小时的图片删除。
{
  "sql": "SELECT * from demo",
  "actions": [
    {
      "image": {
        "path": "/tmp",
        "format": "png",
        "filePrefix":"image"
        "maxage":72
      }
    }
  ]
}

**Comment by EMQmyd** [comment]
| 属性名称   | 是否可选 | 说明                                                         |
| ---------- | -------- | ------------------------------------------------------------ |
| path       | 是       | 保存结果的文件夹路径，例如  `/tmp`                           |
| format     | 否       | 文件格式，支持 jpeg 和 png。                                 |
| maxAge     | 是       | 最长文件存储时间(小时)。默认值为72，这表示图片最多保存3天。  |
| filePrefix | 是       | 图片文件名前缀,默认为 image，文件格式样例为 image_2020-12-12_11-15-23-345.png |

**Comment by ngjaying** [comment]
This was supported in [1.1.0](https://github.com/emqx/kuiper/releases/tag/1.1.0) so closed.
