### ISSUE TITLE
Are UDF and UDFAF supported

### ISSUE THREAD

**Issue by cmdares** [emqx/kuiper#646]

**Comment by jinfahua** [comment]
Yes, it's supported. You can refer [plugin development tutorial](https://github.com/emqx/kuiper/blob/master/docs/zh_CN/plugins/plugins_tutorial.md) for how to write a customized plugin. Also, please refer to [function interfaces](https://github.com/emqx/kuiper/blob/master/docs/zh_CN/extension/function.md) .

**Comment by ngjaying** [comment]
Close. Please reopen if you have more queries.
