### ISSUE TITLE
Can 【tools/kubernetes】support update rule ?

### ISSUE THREAD

**Issue by smart33690** [emqx/kuiper#650]
In kuiper rule documents  https://docs.emqx.cn/cn/kuiper/latest/restapi/rules.html about updating rule。
![image](https://user-images.githubusercontent.com/31605966/102194823-b6865300-3ef8-11eb-8317-9166e374fcd1.png)

In tools/kubernetes https://github.com/emqx/kuiper/tree/master/tools/kubernetes can support  update rule？

**Comment by EMQmyd** [comment]
https://github.com/emqx/kuiper/pull/659

**Comment by EMQmyd** [comment]
1.0.3 version already supported
