### ISSUE TITLE
extended plugin didnot load at all

### ISSUE THREAD

**Issue by liqiang000** [emqx/kuiper#661]
Kuiper team developers, I developed customized source plugin and sink plugin based on Kuiper interface. 
I test it with examples/testExtension.go, it worked as expected, it can capture the defined stream and feed it to sink plugin. 

My question is when I use kuiper cli or rest api for creating stream and rule (instead of using example/testExtension.go as trigger), the stream and rule are both created ok. 
However, the kuiperd seems to not open required plugins successfully and no errors log found. it didn't capture the required stream at all. 
After reading the docs, I din't find the solution.

Give me a suggestion, please. Any replies will be thankfull. 

misc: 

1 kuiper v1.0.2.
2 kuiper docker images created by make docker.

**Comment by ngjaying** [comment]
Hi liqiang, 
If the plugin is not loaded, there should be errors in the log. What did you see in the rule status by [REST: get rule status](https://github.com/emqx/kuiper/blob/master/docs/en_US/restapi/rules.md#get-the-status-of-a-rule)

**Comment by liqiang000** [comment]
sorry for late reply. I followed your instruction with
 curl http://127.0.0.1:9081/rules/{id}/status. It sometimes blocked. Even using Kuiper cli instructions will encounter the similar blocking status.

After killing the process, restart the process. Drop the rule. Create it again. Check the status with “bin/kuiper getstatus rule”. The console prints log like this “Connecting to 127.0.0.1:20498…”. It seems that it is blocked. Now all the kuiperd’s log is output into console. So it’s easy to find whether the error level log had been output.

Btw，event I got the response with rest API, the written plugin did not auto work. I am deeply confused about this.

The above description is what I saw. Maybe I misused. I am trying to find the right path.

**Comment by liqiang000** [comment]
add, "the log level is set debug".

**Comment by ngjaying** [comment]
@liqiang000 I don't quite understand your reply. Did you get the log or console log? Could you attach them? What did you get of getStatus for a common rule without using your custome plugin? 
For general plugin development and deployment, refer to [plugin tutorial](https://github.com/emqx/kuiper/blob/master/docs/zh_CN/plugins/plugins_tutorial.md) for more detail.

**Comment by liqiang000** [comment]
@ngjaying   Thanks for you echo. With the builtin plugins, like mqtt source, it works well.
I have a question for plugin deployment. As the [docs](https://github.com/emqx/kuiper/blob/master/docs/zh_CN/plugins/plugins_tutorial.md#%E6%8F%92%E4%BB%B6%E9%83%A8%E7%BD%B2) states, it must be packaged in zip form. Now I just compiled it and copy it into corresponding plugins dir. Does this work?

**Comment by ngjaying** [comment]
> As the [docs](https://github.com/emqx/kuiper/blob/master/docs/zh_CN/plugins/plugins_tutorial.md#%E6%8F%92%E4%BB%B6%E9%83%A8%E7%BD%B2) states, it must be packaged in zip form. Now I just compiled it and copy it into corresponding plugins dir

I assume you are develop and test in the local environment. Then the zip is no needed, it is only for REST/CLI api. Just put the so file and the config yaml file in the correct path and restart kuiperd to load. For example, build your sink to the kuiper plugins/sinks path by setting the -o path in go build.  `go build --buildmode=plugin -o $kuiperPath/_build/$build/plugins/sinks/Mysql@v1.0.0.so sinks/mysql.go`. Remember to replace $kuiperPath and $build to your local path. For source, remember to also provide a yaml file in etc/sources.

**Comment by liqiang000** [comment]
@ngjaying Ok. Placing plugin position correctly was assured. Using example/testExtension.go tool for testing developed plugin works as expected. Now I use windows feature in sql like “SELECT count(*) from teststream where teststream.txInfo->ledgerid=mychannel group by TUMBLINGWINDOW(ss, 50)” under bin/kuiper query cli. No results echoed even the defined stream came. It’s weired. Later, I can offer some logs for inspecting.

**Comment by liqiang000** [comment]
@ngjaying After creating rule, Kuiper cli’s output:
```
Creating a new rule from file test_rule.txt.
call rpc server ....
Rule fabricrule was created successfully, please use 'bin/kuiper getstatus rule fabricrule' command to get rule status.
```

And running “bin/kuiper getstatus rule fabricrule”, kuiper cli’output:
`Connecting to 127.0.0.1:20498…`

No further logs output on kuiper cli side, it is blocking.

The attached file is kuiperd's output. 
[5214F7AE-3142-4B86-912D-039E88B9E66C.txt](https://github.com/emqx/kuiper/files/5756608/5214F7AE-3142-4B86-912D-039E88B9E66C.txt)

The above operations contains stream creation, rule creation.

**Comment by ngjaying** [comment]
The log looks fine but it seems no data is fed from source. Is kuiperd still running? If it crashed, you should get some logs in its console. If kuiperd is still alive, what can you get for cli `show rules` or `show streams`? What about REST api result.

**Comment by liqiang000** [comment]
@ngjaying Yes, no input. I feed stream data into source plugin(to some extent, I am sure the extended plugin is not running due to no corresponding log output in customized plugin.), the kuiperd’s log also did not change at all. Kuiperd is alive by checking its port(20498) . I also checked cli, but they(bin/kuiper show streams、bin/kuiper show rules) are both blocked(But if restart, they are normal).

**Comment by ngjaying** [comment]
How about the REST API? After restart, what can you get from `show rules`? Is your rule running? If it is all fine without using your plugin, I suspect something in your code might cause the problem.

**Comment by liqiang000** [comment]
btw，curl http://127.0.0.1:9081/ping. It also blocked.

**Comment by liqiang000** [comment]
add, after restart, bin/kuiper show rules output:
Connecting to 127.0.0.1:20498... 
So far, connection established
```
[
  {
    "id": "fabricrule",
    "status": "Running"
  }
]
```

**Comment by ngjaying** [comment]
Do you modify the codes because I find many logs that are not in the original codes?
I review the log, the plugin seems not fully loaded. It stops at:

`time="2020-12-31 06:18:41" level=debug msg="Opening plugin /kuiper/plugins/sinks/file@v1.0.0.so" file="plugins/manager.go:119"`

You should get "Successfully look-up plugin" in the debug log to fully loaded a plugin. Do you build the plugin in the exaxt same environment of the running kuiper? If you running kuiper is in a docker image, you need to build the plugin in the same docker image. There are a lot of limitations of the go plugin, please read plugin tutorial for more detail. If you are in the development phase, recommend to clone the code and build/run kuiper and plugins in the same local machine.

**Comment by liqiang000** [comment]
@ngjaying Thanks for your patience. Yes, I added additional logs for debug. Plugin built process happens kuiper . I add the following instructions in deploy/docker/Dockerfile-alpine file

```
RUN go build -buildmode=plugin -o _build/kuiper-*/plugins/sources/fabricSource@v0.0.1.so plugins/sources/fabric/fabric.go
# compile fabric sink plugin
RUN go build -buildmode=plugin -o _build/kuiper-*/plugins/sinks/fabricSink@v0.0.1.so plugins/sinks/fabric/fabric.go
# compile file as sink plugin
RUN go build --buildmode=plugin -o _build/kuiper-*/plugins/sinks/file@v1.0.0.so plugins/sinks/file/file.go
RUN GO111MODULE=on go build -o _build/kuiper-*/bin/example examples/testSource/testExtension.go
```
 

btw, My plugin project is located in the kuiper project. The point is that I use the examples/testExtension.go for triggering the single plugin, feed the stream, it worked(such as capturing the stream data).

**Comment by ngjaying** [comment]
Just to confirm, all your runnings happen in the docker alpine container, correct? Can you please paste the full log of both the testExtension run and normal rule run？

You may also want to try Dockerfile-slim instead of alpine.

**Comment by liqiang000** [comment]
The following output from example/testExtension.go.
```
time="2021-01-04 02:57:35" level=info msg="kuiper confDir[/kuiper/etc/], kuiper config file path[/kuiper/etc/kuiper.yaml]" file="common/util.go:51"
time="2021-01-04 02:57:35" level=info msg="kuiper log file path[/kuiper/log/stream.log]" file="common/util.go:151"
time="2021-01-04 02:57:35" level=info msg="conf init done" file="testSource/testExtension.go:15"
time="2021-01-04 02:57:35" level=info msg="db location is /kuiper/data/" file="testSource/testExtension.go:20"
time="2021-01-04 02:57:35" level=info msg="stream fabricstream dropped" file="testSource/testExtension.go:27"
time="2021-01-04 02:57:35" level=info msg="Stream fabricstream is created." file="processors/xsql_processor.go:75"
time="2021-01-04 02:57:35" level=info msg="common.Config ? = nil[false]" file="processors/xsql_processor.go:324"
time="2021-01-04 02:57:35" level=info msg="rule[fabricrule], rule json[{ \"sql\": \"select count(*) from fabricstream where fabricstream.txInfo->ledgerID = mychannel group by TUMBLINGWINDOW(ss, 50)\", \"actions\": [ { \"file\": { \"path\": \"/kuiper/fabricresult.txt\", \"interval\": 1000 } } ] }]" file="processors/xsql_processor.go:325"
time="2021-01-04 02:57:35" level=debug msg="delete cache key fabricrulefile_00" file="processors/xsql_processor.go:477"
time="2021-01-04 02:57:35" level=info msg="common.Config ? = nil[false]" file="processors/xsql_processor.go:324"
time="2021-01-04 02:57:35" level=info msg="rule[fabricrule], rule json[{ \"sql\": \"select count(*) from fabricstream where fabricstream.txInfo->ledgerID = mychannel group by TUMBLINGWINDOW(ss, 50)\", \"actions\": [ { \"file\": { \"path\": \"/kuiper/fabricresult.txt\", \"interval\": 1000 } } ] }]" file="processors/xsql_processor.go:325"
time="2021-01-04 02:57:35" level=info msg="Rule fabricrule is created." file="processors/xsql_processor.go:239"
time="2021-01-04 02:57:35" level=info msg="Init rule with options &{IsEventTime:false LateTol:1000 Concurrency:1 BufferLength:1024 SendMetaToSink:false Qos:0 CheckpointInterval:300000}" file="planner/planner.go:23"
time="2021-01-04 02:57:35" level=info msg="rule init done, open plugin ..." file="testSource/testExtension.go:58"
time="2021-01-04 02:57:35" level=info msg="Opening stream" file="xstream/streams.go:141" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="open sink node file_0" file="nodes/sink_node.go:73" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Unary operator 1_preprocessor_fabricstream is started" file="nodes/operations.go:53" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Window operator 2_window is started" file="nodes/window_op.go:75" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Restore window state, nothing" file="nodes/window_op.go:94" rule=fabricrule
time="2021-01-04 02:57:35" level=info msg="open sink node 1 instances" file="nodes/sink_node.go:164" rule=fabricrule
time="2021-01-04 02:57:35" level=info msg="Start with window state triggerTime: 0, msgCount: 0" file="nodes/window_op.go:117" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Unary operator 3_filter is started" file="nodes/operations.go:53" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Unary operator 4_project is started" file="nodes/operations.go:53" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Trying to get sink for rule fabricrule with options map[interval:1000 path:/kuiper/fabricresult.txt]\n" file="nodes/sink_node.go:170" rule=fabricrule
time="2021-01-04 02:57:35" level=info msg="open source node fabricstream with option map[CONF_KEY:default DATASOURCE:fabric FORMAT:json TYPE:fabricSource]" file="nodes/source_node.go:59" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="confPath[sources/fabricSource.yaml]" file="nodes/source_node.go:221" rule=fabricrule
time="2021-01-04 02:57:35" level=info msg="plugin key[sinks/file], symbol name[File]" file="plugins/manager.go:100"
time="2021-01-04 02:57:35" level=info msg="kuiper confDir[/kuiper/etc/], kuiper config file path[/kuiper/etc/sources/fabricSource.yaml]" file="common/util.go:51"
time="2021-01-04 02:57:35" level=info msg="all available plugin:map[]" file="plugins/manager.go:105"
time="2021-01-04 02:57:35" level=info msg="init plugin mgr" file="plugins/manager.go:107"
time="2021-01-04 02:57:35" level=info msg="plugin dir[/kuiper/plugins]" file="plugins/manager.go:207"
time="2021-01-04 02:57:35" level=debug msg="found conf w.r.t key[default]" file="nodes/source_node.go:237" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="get conf for fabricSource with conf key default: map[channels:map[mychannel:map[orderers:[orderer] peers:map[peer0.org1.example.com:map[chaincodeQuery:true endorsingPeer:true eventSource:true ledgerQuery:true]] policies:map[queryChannelConfig:map[maxTargets:1 minResponses:1 retryOpts:map[attempts:5 backoffFactor:2 initialBackoff:500ms maxBackoff:5s]]]]] client:map[BCCSP:map[security:map[default:map[provider:SW] enabled:true ephemeral:false hashAlgorithm:SHA2 level:256 softVerify:true]] credentialStore:map[cryptoStore:map[path:/kuiper/crypto-config/state-store] path:/kuiper/crypto-config/state-store] cryptoconfig:map[path:/kuiper/crypto-config] eventService:map[timeout:map[connection:30s registrationResponse:30s]] global:map[cache:map[channelConfig:60s channelMembership:30s connectionIdle:30s eventServiceIdle:2m] timeout:map[execute:60s query:45s resmgmt:60s]] logging:map[level:info] name:User1 orderer:map[timeout:map[connection:30s response:30s]] organization:Org1 peer:map[timeout:map[connection:30s discovery:map[greylistExpiry:5s] response:40s]] tls:map[enabled:true] tlsCerts:map[client:map[cert:map[path:/kuiper/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt] key:map[path:/kuiper/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key]] path: pem:[]]] format:json orderers:map[orderer:map[grpcOptions:map[allow-insecure:false fail-fast:false keep-alive-permit:false keep-alive-time:0s keep-alive-timeout:20s ssl-target-name-override:orderer.example.com] tlsCACerts:map[path:/kuiper/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem] url:orderer.example.com:7050]] organizations:map[OrdererOrg:map[certificateAuthorities:[] cryptoPath:ordererOrganizations/example.com/users/User1@example.com/msp mspid:ordererMSP peers:[]] Org1:map[certificateAuthorities:[ca] cryptoPath:peerOrganizations/org1.example.com/users/User1@org1.example.com/msp mspid:Org1MSP peers:[peer0.org1.example.com]]] peers:map[peer0.org1.example.com:map[grpcOptions:map[allow-insecure:false fail-fast:false keep-alive-permit:false keep-alive-time:0s keep-alive-timeout:20s ssl-target-name-override:peer0.org1.example.com] tlsCACerts:map[path:/kuiper/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem] url:peer0.org1.example.com:7051]] version:1.0.0]" file="nodes/source_node.go:255" rule=fabricrule
time="2021-01-04 02:57:35" level=info msg="open source node 1 instances" file="nodes/source_node.go:81" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="got source plugin" file="plugins/manager.go:138"
time="2021-01-04 02:57:35" level=info msg="plugin key[sources/fabricSource], symbol name[FabricSource]" file="plugins/manager.go:100"
time="2021-01-04 02:57:35" level=info msg="found a plugin[map[fabricSource:v0.0.1]]" file="plugins/manager.go:217"
time="2021-01-04 02:57:35" level=info msg="found a plugin[map[fabricSink:v0.0.1 file:v1.0.0]]" file="plugins/manager.go:217"
time="2021-01-04 02:57:35" level=info msg="found a plugin[map[]]" file="plugins/manager.go:217"
time="2021-01-04 02:57:35" level=info msg="print all internal plugins:[map[fabricSource:v0.0.1] map[fabricSink:v0.0.1 file:v1.0.0] map[]]" file="plugins/manager.go:224"
time="2021-01-04 02:57:35" level=info msg="file path in yaml[/kuiper/etc/mqtt_source.yaml]" file="plugins/sourceMeta.go:92"
time="2021-01-04 02:57:35" level=info msg="file path in yaml[/kuiper/etc/sources/edgex.yaml]" file="plugins/sourceMeta.go:92"
time="2021-01-04 02:57:35" level=info msg="sourceMeta file : edgex.json" file="plugins/sourceMeta.go:136"
time="2021-01-04 02:57:35" level=info msg="file path in yaml[/kuiper/etc/sources/httppull.yaml]" file="plugins/sourceMeta.go:92"
time="2021-01-04 02:57:35" level=info msg="sourceMeta file : httppull.json" file="plugins/sourceMeta.go:136"
time="2021-01-04 02:57:35" level=info msg="file path in yaml[/kuiper/etc/sources/random.yaml]" file="plugins/sourceMeta.go:92"
time="2021-01-04 02:57:35" level=info msg="sourceMeta file : random.json" file="plugins/sourceMeta.go:136"
time="2021-01-04 02:57:35" level=info msg="file path in yaml[/kuiper/etc/sources/zmq.yaml]" file="plugins/sourceMeta.go:92"
time="2021-01-04 02:57:35" level=info msg="sourceMeta file : zmq.json" file="plugins/sourceMeta.go:136"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: edgex.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: file.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: influx.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: log.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: mqtt.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: nop.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: options.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: properties.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: rest.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: tdengine.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="Loading metadata file for sink: zmq.json" file="plugins/sinkMeta.go:291"
time="2021-01-04 02:57:35" level=info msg="funcMeta file : accumulateWordCount.json" file="plugins/funcMeta.go:106"
time="2021-01-04 02:57:35" level=info msg="funcMeta file : countPlusOne.json" file="plugins/funcMeta.go:106"
time="2021-01-04 02:57:35" level=info msg="funcMeta file : echo.json" file="plugins/funcMeta.go:106"
time="2021-01-04 02:57:35" level=info msg="funcMeta file : internal.json" file="plugins/funcMeta.go:106"
time="2021-01-04 02:57:35" level=info msg="funcMeta file : windows.json" file="plugins/funcMeta.go:106"
time="2021-01-04 02:57:35" level=info msg="uiMsg file : en_US.ini" file="plugins/msg_util.go:37"
time="2021-01-04 02:57:35" level=info msg="uiMsg file : zh_CN.ini" file="plugins/msg_util.go:37"
time="2021-01-04 02:57:35" level=info msg="plugin type[sinks], plugin name[file]" file="plugins/manager.go:113"
time="2021-01-04 02:57:35" level=info msg="plugin list in registry:[map[fabricSource:v0.0.1] map[fabricSink:v0.0.1 file:v1.0.0] map[]]" file="plugins/manager.go:390"
time="2021-01-04 02:57:35" level=info msg="plugin path[/kuiper/plugins/sinks/file@v1.0.0.so]" file="plugins/manager.go:401"
time="2021-01-04 02:57:35" level=debug msg="Opening plugin /kuiper/plugins/sinks/file@v1.0.0.so" file="plugins/manager.go:119"
time="2021-01-04 02:57:35" level=debug msg="Successfully open plugin /kuiper/plugins/sinks/file@v1.0.0.so" file="plugins/manager.go:125"
time="2021-01-04 02:57:35" level=debug msg="Successfully look-up plugin /kuiper/plugins/sinks/file@v1.0.0.so" file="plugins/manager.go:130"
time="2021-01-04 02:57:35" level=info msg="plugin symbol w.r.t. [sinks/file] found" file="plugins/manager.go:133"
time="2021-01-04 02:57:35" level=info msg="all available plugin:map[sinks/file:0x7f52c34c0690]" file="plugins/manager.go:105"
time="2021-01-04 02:57:35" level=info msg="init plugin mgr" file="plugins/manager.go:107"
time="2021-01-04 02:57:35" level=info msg="plugin type[sources], plugin name[fabricSource]" file="plugins/manager.go:113"
time="2021-01-04 02:57:35" level=info msg="plugin list in registry:[map[fabricSource:v0.0.1] map[fabricSink:v0.0.1 file:v1.0.0] map[]]" file="plugins/manager.go:390"
time="2021-01-04 02:57:35" level=info msg="sink actions:map[interval:1000 path:/kuiper/fabricresult.txt]" file="nodes/sink_node.go:419"
time="2021-01-04 02:57:35" level=debug msg="Successfully get the sink file" file="nodes/sink_node.go:176" rule=fabricrule
time="2021-01-04 02:57:35" level=info msg="plugin path[/kuiper/plugins/sources/fabricSource@v0.0.1.so]" file="plugins/manager.go:401"
time="2021-01-04 02:57:35" level=debug msg="Now is to open sink for rule fabricrule.\n" file="nodes/sink_node.go:180" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Opening file sink" file="file/file.go:41" rule=fabricrule
time="2021-01-04 02:57:35" level=debug msg="Opening plugin /kuiper/plugins/sources/fabricSource@v0.0.1.so" file="plugins/manager.go:119"
time="2021-01-04 02:57:35" level=debug msg="Successfully open sink for rule fabricrule.\n" file="nodes/sink_node.go:185" rule=fabricrule
time="2021-01-04 02:57:36" level=debug msg="Successfully open plugin /kuiper/plugins/sources/fabricSource@v0.0.1.so" file="plugins/manager.go:125"
time="2021-01-04 02:57:36" level=debug msg="Successfully look-up plugin /kuiper/plugins/sources/fabricSource@v0.0.1.so" file="plugins/manager.go:130"
time="2021-01-04 02:57:36" level=info msg="plugin symbol w.r.t. [sources/fabricSource] found" file="plugins/manager.go:133"
```
 
From the log, it is easy to find that the source plugin loaded well.
 
this is the rule.
`ruleJson := "{ \"sql\": \"select count(*) from fabricstream where fabricstream.txInfo->ledgerID = mychannel group by TUMBLINGWINDOW(ss, 50)\", \"actions\": [ { \"file\": { \"path\": \"/kuiper/fabricresult.txt\", \"interval\": 1000 } } ] }"`
 
tricky thing is when I change it for this one(add escape character).
```
ruleJson := "{ \"sql\": \"select count(*) from fabricstream where fabricstream.txInfo->ledgerID = "\mychannel\" group by TUMBLINGWINDOW(ss, 50)\", \"actions\": [ { \"file\": { \"path\": \"/kuiper/fabricresult.txt\", \"interval\": 1000 } } ] }"
the test/Extension.go panic.
```
 
 
Now I can receive the stream data, but not analysis result found in /kuiper/fabricresult.txt (such as how many records got in last 50 seconds). I did not know whether the sql is not desired one what I expect.  If something wrong, correct me please.

**Comment by ngjaying** [comment]
> tricky thing is when I change it for this one(add escape character).

The escape is wrong `fabricstream.txInfo->ledgerID = "\mychannel\"` should be `fabricstream.txInfo->ledgerID = \"mychannel\"`

> Now I can receive the stream data, but not analysis result found
Your filter `where fabricstream.txInfo->ledgerID = mychannel` will compare the ledgerID with myChannel field. If you aim to compare with string literal "myChannel", this condition will never meet so that you won't get any output.

**Comment by liqiang000** [comment]
I use the modified rule in test/testExtension.go,but got error:

`time="2021-01-04 06:02:32" level=info msg="failed to create rule: Parse rule { \"sql\": \"select count(*) from fabricstream where fabricstream.txInfo->ledgerID = \"mychannel\" group by TUMBLINGWINDOW(ss, 50)\", \"actions\": [ { \"file\": { \"path\": \"/kuiper/fabricresult.txt\", \"interval\": 1000 } } ] } error : invalid character 'm' after object key:value pair.." file="testSource/testExtension.go:50"`

The following is the stream definition:
```
fabricstream(
    blockHash STRING,
    blockHeight bigint,
    previousBlockHash string,
    txInfo STRUCT(ledgerID string, txId string, txIdex bigint, txTime string),
    envelopeDetail  array(struct(chaincode string, version string, cclang string, method string, args array(string)))
  ) WITH (DATASOURCE="fabric", FORMAT="json", TYPE="fabricSource", CONF_KEY="default")`
```

**Comment by ngjaying** [comment]
> { \"sql\": \"select count(*) from fabricstream where fabricstream.txInfo->ledgerID = \"mychannel\" group by TUMBLINGWINDOW(ss, 50)\", \"actions\": [ { \"file\": { \"path\": \"/kuiper/fabricresult.txt\", \"interval\": 1000 } } ] }

Your json is invalid, should be
`"{ \"sql\": \"select count(*) from fabricstream where fabricstream.txInfo->ledgerID = \\\"mychannel\\\" group by TUMBLINGWINDOW(ss, 50)\", \"actions\": [ { \"file\": { \"path\": \"/kuiper/fabricresult.txt\", \"interval\": 1000 } } ] }"`

**Comment by liqiang000** [comment]
with the right json format you provided, file sink got the result. thanks a lot.  It's progessive.  But the truly tricky problem(plugins cannot auto load) is troubling me. It seems that the work mechanism of test/Extension.go is independent of kuiperd. without not kuiperd, it also can work.

**Comment by ngjaying** [comment]
It could be a compatibility problem of alpine. Could you please try with other docker image or just try locally?

**Comment by liqiang000** [comment]
OK. now I try Dockerfile-slim.

**Comment by liqiang000** [comment]
@ngjaying it is ok with Dockerfile-slim as base. alpine is still not. many thanks for your help.

**Comment by ngjaying** [comment]
We recommend NOT to use alpine if building customized plugin due to the restriction of alpine/go combination. If you do need to use alpine, [this](https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host) may be helpful.

**Comment by liqiang000** [comment]
Got it. thanks.
