### ISSUE TITLE
Wrong description in stream document.

### ISSUE THREAD

**Issue by Bluejoy608** [emqx/kuiper#675]
File: [/docs/en_US/cli/streams.md](https://docs.emqx.io/en/kuiper/latest/cli/streams.html)

"The command create a rule named my_stream."
should be changed to 
"The command create a stream named my_stream."

This problem also in Chinese document.

![图片](https://user-images.githubusercontent.com/36184822/103397466-7cad8180-4b73-11eb-9190-260da5fa2a5f.png)

**Comment by jinfahua** [comment]
Thanks for your feedback, we'll fix it in next release.

**Comment by EMQmyd** [comment]
https://github.com/emqx/kuiper/pull/676
