### ISSUE TITLE
kuiper1.0.1 reports error when the password is number

### ISSUE THREAD

**Issue by craysZ** [emqx/kuiper#677]
File: [/docs/zh_CN/restapi/rules.md](https://docs.emqx.cn/cn/kuiper/latest/restapi/rules.html)

closing rule rule0001 for error: read properties map[concurrency:1 password:111111 qos:1 servers:[tcp://172.0.0.1:1883] sharedSubscription:true username:root] fail with error: json: cannot unmarshal number into Go struct field MQTTConfig.password of type string" file="server/ruleManager.go:69

**Comment by jinfahua** [comment]
Could you please try to enclose your password with quotes? E,g , as following,
```yaml
  username: root
  password: "111111"
```

**Comment by craysZ** [comment]
> Could you please try to enclose your password with quotes? E,g , as following,
> 
> ```yaml
>   username: root
>   password: "111111"
> ```

![image](https://user-images.githubusercontent.com/18133348/103839562-a82bf100-50ca-11eb-88fa-c587da0e237b.png)
The JSON data has "" and Kuiper received it and escaped it incorrectly

**Comment by jinfahua** [comment]
You sink configuration looks good. Could you please check the password setting in configuration file `etc/mqtt_source.yaml`?

**Comment by craysZ** [comment]
> Your sink configuration looks good. Could you please check the password setting in configuration file `etc/mqtt_source.yaml`?

Thank you very much. The  error is from the source config.
