### ISSUE TITLE
Question on kuiper SQL

### ISSUE THREAD

**Issue by liqiang000** [emqx/kuiper#680]
@ngjaying Hi, kuiper team. I have a requirement. I want to filter single stream data meeting customized external criteria(this criteria cannot extract from stream itself). Put simply, I use kuiper sql to filter data items from stream for what I expect. But I will further check the filtered data item against the external data. If found a match at this point, I will output it into sink plugin. I don’t know whether kuiper support this. 

Looking forward to u echo.

**Comment by jinfahua** [comment]
I think you can extend a function, and the function can load the external system data. To improve performance, you can cache your external data into memory after loading them from the external systems.

**Comment by liqiang000** [comment]
@jinfahua I probably have an idea. I add a new source plugin for feed the external criteria. And I use the left join ability for selecting the expected stream from other source plugin in kuiper sql.

**Comment by jinfahua** [comment]
> @jinfahua I probably have an idea. I add a new source plugin for feed the external criteria. And I use the left join ability for selecting the expected stream from other source plugin in kuiper sql.

It's sounds a great idea :-)

**Comment by liqiang000** [comment]
Basically, extending a function is ok, but the subtle point is that the criteria is dynamic(at least we expect it to be) not static. If extending source plugins looks good, I will do. Many thanks.

**Comment by jinfahua** [comment]
It has problem with join solution - the join only make sense when you using window (e,g, time window).

**Comment by liqiang000** [comment]
Yes, I agree with you. Besides slack，is there any place(like, wechat group) available for kuiper discussion? I wanna join one.

**Comment by ngjaying** [comment]
We introduced [Table](https://github.com/emqx/kuiper/blob/master/docs/en_US/sqls/tables.md#lookup-table) in v1.2.0. You can use it as a lookup dictionary, this may meet your requirement.
