### ISSUE TITLE
The extended function plugin does not support * parameter

### ISSUE THREAD

**Issue by feng-crazy** [emqx/kuiper#685]
通过插件扩展了一个函数myfunc，使用sql语句
(SELECT myfunc(\*) FROM test;)
传入myfunc的参数是["\*"],并不是来自test流的数据

**Comment by hedengfeng** [comment]
通过插件扩展了一个函数myfunc，使用sql语句
SELECT myfunc(*) FROM test;
传入myfunc的参数是"*",并不是来自test流的数据

**Comment by jinfahua** [comment]
Thanks for report the issue, currently the extended functions do not support `*` parameter.

**Comment by hedengfeng** [comment]
> Thanks for report the issue, currently the extended functions do not support `*` parameter. We'll make it extensible in future release.

ok

**Comment by hedengfeng** [comment]
> > Thanks for report the issue, currently the extended functions do not support `*` parameter. We'll make it extensible in future release.
> 
> ok



> Thanks for report the issue, currently the extended functions do not support `*` parameter. We'll make it extensible in future release.

How to join your developer community or support community for WeChat?

**Comment by ngjaying** [comment]
Released in v1.2.0 so closed
