### ISSUE TITLE
meta field from DefaultSourceTuple possibly unused

### ISSUE THREAD

**Issue by darkodraskovic** [emqx/kuiper#691]
It is not clear to me how to use `meta` from `DefaultSourceTuple`. It seems that only `message` is forwarded as `item` in the sink.

**Comment by ngjaying** [comment]
The meta data can be used in

1. SQL with meta(prop) function. The user can use the meta to filter data or select the meta to output. `select meta(device) as d from demo where meta(deviceId)="anid"`. Please check [Built in functions] (https://github.com/emqx/kuiper/blob/master/docs/en_US/sqls/built-in_functions.md) for detail.
2. Send directly to the sink result by specifying the `sendMetaToSink` option for the rule. Please check [rule options](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/overview.md#options) for detail.

**Comment by darkodraskovic** [comment]
Thank you very much. I'm closing the issue.
