### ISSUE TITLE
Test Sessionwindow happens panic：panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by swing99527** [emqx/kuiper#692]
Logs:
time="2021-01-21 08:34:55" level=info msg="Successfully subscribe to topic /v1/+/service/data/TTAH" file="extensions/mqtt_source.go:193" rule=internal-xstream_query_rule
time="2021-01-21 08:34:55" level=info msg="Successfully subscribe to topic tcp://192.168.1.226:1883: 89ad3bf0-5bc3-11eb-9ff0-0242ac110002" file="extensions/mqtt_source.go:157" rule=internal-xstream_query_rule
panic: runtime error: index out of range [0] with length 0

goroutine 55 [running]:
github.com/emqx/kuiper/xstream/nodes.(*WindowOperator).execProcessingWindow(0x40002e2aa0, 0xfbca20, 0x4000381730, 0x0, 0x0, 0x0, 0x40002f4540)
	/go/kuiper/xstream/nodes/window_op.go:280 +0x19bc
created by github.com/emqx/kuiper/xstream/nodes.(*WindowOperator).Exec
	/go/kuiper/xstream/nodes/window_op.go:121 +0x4c8

Sql:SELECT * from TTAH GROUP BY SESSIONWINDOW(ss, 10,10)
Stream: bin/kuiper create stream TTAH '(deviceId string,param  STRUCT(deviceId STRING, data STRUCT(Tmp float, Hum float)))WITH (DATASOURCE="/v1/+/service/data/TTAH", FORMAT="JSON", STRIC
T_VALIDATION="false", CONF_KEY="default")'

**Comment by ngjaying** [comment]
Hi @swing99527,

Thanks for opening the issue. /window_op.go:280 is a debug log. Just to confirm, are you running in debug mode? What version do you use?

**Comment by swing99527** [comment]
> Hi @swing99527,
> 
> Thanks for opening the issue. /window_op.go:280 is a debug log. Just to confirm, are you running in debug mode? What version do you use?

version: docker kuiper 1.1.1-alpine,
and after panic happend, container exit
How can I check whether run in debug mode?
