### ISSUE TITLE
Sending flat map to consumer channel in source, receiving encoded slice in sink

### ISSUE THREAD

**Issue by darkodraskovic** [emqx/kuiper#695]
I've made a custom source where I forward a flat map to kuiper. Map looks similar to this: `{"bn":"rules-engine","n":"voltage","v":120.1}`. However, in the sink I'm receiving something similar to this: `[{"bn":"rules-engine","n":"voltage","v":120.1}]` (in an encoded form, so I have to unmarshal it).

My question is why do we need to receive a slice in a sink if we cannot send a slice in a source.

**Comment by jinfahua** [comment]
Because Kuiper supports aggregation functions, such as time windows, so the sink result could be possibly have multiple records. Please refer to doc - https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/data_template.md for split array to single records.

**Comment by jinfahua** [comment]
Supporting for sending a slice into source is tracking in this issue - https://github.com/emqx/kuiper/issues/605

**Comment by ngjaying** [comment]
Just add one point, by setting [sendSingle](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/overview.md#sinksactions) property to the sink action, the resulte will be flatten.

**Comment by ngjaying** [comment]
Close this since the question is answered. Please reopen if you still have more queries. Thanks.
