### ISSUE TITLE
Docker compose Env variables not working

### ISSUE THREAD

**Issue by RBrothersBSI** [emqx/kuiper#700]
Trying to use docker compose to launch and place the MQTT_SOURCE__DEFAULT__SERVERS=[tcp://broker.emqx.io:1883] under the environment field in the yaml file. It throws an error that this certain environment variable should be a string, not an array of strings.

**Comment by jovdipp** [comment]
> Trying to use docker compose to launch and place the MQTT_SOURCE__DEFAULT__SERVERS=[tcp://broker.emqx.io:1883] under the environment field in the yaml file. It throws an error that this certain environment variable should be a string, not an array of strings.

Hi @RBrothersBSI, is the value set in quotes ?

**Comment by RBrothersBSI** [comment]
Have tried setting them like

environment:
 MQTT_SOURCE__DEFAULT__SERVERS: ['tcp://broker.emqx.io:1883']

and 
environment:
 MQTT_SOURCE__DEFAULT__SERVERS: 
    - 'tcp://broker.emqx.io:1883'

**Comment by jovdipp** [comment]
sorry @RBrothersBSI, I see that value is set as an array/list.

**Comment by RBrothersBSI** [comment]
I have also tried with just a string value, which allowed it to run, but it didn't seem to pick up that the variable had been set when I ran docker-compose up.

**Comment by RBrothersBSI** [comment]
I checked the logs after running and it didn't seem like it picked up the value.

**Comment by jovdipp** [comment]
@RBrothersBSI which version are you using ?

**Comment by RBrothersBSI** [comment]
That was it! Was using 1.1.0-slim and upgraded to 1.1.1-slim and it worked perfectly. Thank you for the quick response.
