### ISSUE TITLE
props map[string]interface{} not configurable via RESTAPI

### ISSUE THREAD

**Issue by darkodraskovic** [emqx/kuiper#715]
When we create custom source plugins, we implement method

```
Configure(datasource string, props map[string]interface{}) error
```
of the `type Source interface`. `props map[string]interface{}` is configured with a file found in `etc/sources/<plugin>.yaml`. However, there is no option to configure the props via RESTAPI. We can only use a "a json string with sql field" (see [here](https://github.com/emqx/kuiper/blob/master/docs/en_US/restapi/streams.md#create-a-stream)).

One should be able to configure it with RESTAPI.

**Comment by jinfahua** [comment]
We currently have the API for updating the source yaml configuration file, but we had thought it's only for [kuiper-manager ui](https://hub.docker.com/r/emqx/kuiper-manager), and it's not open for public. The source code is available at [here](https://github.com/emqx/kuiper/blob/master/xstream/server/server/rest.go#L110). You can refer to [this doc](https://github.com/emqx/kuiper/blob/master/docs/en_US/manager-ui/plugins_in_manager.md#plugin-metadata) for more detailed info.

**Comment by darkodraskovic** [comment]
Thank you!
