### ISSUE TITLE
There are some bad links in doc.

### ISSUE THREAD

**Issue by CheolhoJeon** [emqx/kuiper#721]
File: [/docs/en_US/rules/overview.md](https://docs.emqx.io/en/kuiper/latest/rules/overview.html)

**Comment by jinfahua** [comment]
@CrazyWisdom Could you help to take a look? Thanks.

**Comment by CrazyWisdom** [comment]
> @CrazyWisdom Could you help to take a look? Thanks.

Ok.

**Comment by Red-Asuka** [comment]
@CheolhoJeon Thanks, It will be fixed in the next version update.
