### ISSUE TITLE
Wildcard MQTT topic streams

### ISSUE THREAD

**Issue by RBrothersBSI** [emqx/kuiper#730]
Trying to use a wildcard topic with mqtt source. 
Something like: 
    Actual Topic: bldg1/room1/co2
    Stream Datasource: +/+/co2

This does not seem to work. Are wildcards supported?

**Comment by jinfahua** [comment]
It's supported. How do you write the stream definition? Could you please attach the log file if there are any error?

**Comment by RBrothersBSI** [comment]
No errors when creating the stream. I have attached two files, one is of the actual curl request (streams.txt) and the other is of the get request on the stream (wildcard.txt).
 Hope this helps. 
[streams.txt](https://github.com/emqx/kuiper/files/6073009/streams.txt)
[wildcard.txt](https://github.com/emqx/kuiper/files/6073011/wildcard.txt)

**Comment by ngjaying** [comment]
I tried your stream, it works fine. Assume you have created a rule with the stream. Could you please attach your log?

**Comment by RBrothersBSI** [comment]
So, embarrassingly, It looks like my publisher wasn't publishing to the correct topic, on letter off. I re-input the topic on the publishing side and all seemed to work. Thank you very much for the help and love the work!
