### ISSUE TITLE
How to attach Rest data when use Rest sink

### ISSUE THREAD

**Issue by tianxingguo** [emqx/kuiper#736]
Dear ,
  If use  rest sink with method Post, need attach some information, then how to config it with rest sink?

Thanks

**Comment by ngjaying** [comment]
My understanding is that you want to format your post data. Please check the common sink property [dataTemplate](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/overview.md#data-template) and some examples in [rest sink doc](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/sinks/rest.md#rest-action).

**Comment by ngjaying** [comment]
Close. If you have more queries, please reopen it.
