### ISSUE TITLE
search criteria

### ISSUE THREAD

**Issue by craysZ** [emqx/kuiper#737]
Can fuzzy matching be used, such as 'like' in SQL.
 eg:SELECT * FROM t_user WHERE address LIKE '%杭州%'

**Comment by jinfahua** [comment]
Maybe you can use the regexp string functions, please refer to doc - https://github.com/emqx/kuiper/blob/master/docs/en_US/sqls/built-in_functions.md#string-functions

**Comment by craysZ** [comment]
copy that,thanks!
