### ISSUE TITLE
Not Authorized from remote server

### ISSUE THREAD

**Issue by qq420821129** [emqx/kuiper#74]
I have filled the username and password into the mqtt_source.yaml, buf everytime it said to me the result of query is "Not Authorized" when I query from remote server.

**Comment by jinfahua** [comment]
Could you please attach the ``log/stream.log``?

**Comment by jinfahua** [comment]
You could also try the [latest release](https://github.com/emqx/kuiper/releases/tag/0.1.1) see if the problem was fixed or not.

**Comment by jinfahua** [comment]
It has been supported and close the issue.
