### ISSUE TITLE
Question about data retention

### ISSUE THREAD

**Issue by mm-e1** [emqx/kuiper#743]
I noticed that the README says that kuiper can, "save network bandwidth and storage costs".

Is there a data retention policy? At what point is the data removed from kuiper?

Thanks!

**Comment by jinfahua** [comment]
It's benefit from the edge computing - the data are processed near to device, such as in gateway. So only the valued data will be sent over internet after Kuiper processing, and possibly most of data that don't have any value will not be necessary to be transferred to data center.  So if all of data is very important, and need to be sent to data center, this advantage is not very useful.

**Comment by mm-e1** [comment]
Understood. To be clear, data that is not transferred, is automatically deleted?

**Comment by jinfahua** [comment]
No, the data is filter by your business rule - you can write your own business logic with SQL like language.
