### ISSUE TITLE
how to use join correctly

### ISSUE THREAD

**Issue by cntwelve** [emqx/kuiper#755]
Hi, kuiper team:
I have a problem, that I want to filter some data by data itself and another data's history value. The questions are:
1. I think the join clause can help, but i can't find more information about it;
2. Is there any way to extract history data value from stream?

Waiting for your help. Thanks a lot!

**Comment by ngjaying** [comment]
Hi, can you elaborate more about your scenario? How do you get "another data's history value", is it static? If the history values are static, check [table](https://github.com/emqx/kuiper/blob/master/docs/en_US/sqls/tables.md)

**Comment by cntwelve** [comment]
Thanks for your reply. 
The scenario is: there is a sensor(A) that report a status, When the status changed, it raise an event. And there is another sensor(B) that report a measured value, and also reports when value changed. When an event of B arrive, I want to make decision not only using B's value, but also A's status.
So the status of A must retained, or can be obtained from stream history. And I can use join clause to combine the two value.

That's why i want to know how to use join, and where to find historical data.

thanks again.

**Comment by cntwelve** [comment]
Maybe something like table in ksql. Kuiper supports it or not now?

**Comment by ngjaying** [comment]
> Maybe something like table in ksql. Kuiper supports it or not now?

Yes, I agree the continuous table is the right syntax to support your need. It is not supported yet, we will work on it at priority. Currently, you can customized a source in which you can remember the sensarA status and issue your joined sensorA and sensorB data.

**Comment by cntwelve** [comment]
Well, I think what's your mean is, a customized source that has it's own rule for dealing the event, not using kuiper SQL?
I'll try, and I think I prefered the continuous table, beacuse it's more convenient and can make a common sense.

**Comment by cntwelve** [comment]
Another idea, kuiper provide a common function to save certern data in context, then all users can do more things.
Because docs write: "Note: Due to the limitations of Golang plugins, these automatically compiled plugins can run in the container of the corresponding version released by Kuiper. However, for the directly downloaded binary installation package, or the binary package compiled by the user , these downloaded plugins are not guaranteed to work properly. ", so it's better to have a common function in kuiper, :)

**Comment by ngjaying** [comment]
> Well, I think what's your mean is, a customized source that has it's own rule for dealing the event, not using kuiper SQL?
No, a customized source will still work with Kuiper SQL.  Say you created a customized source named mySource, then you can use it to create a stream with `TYPE="mySource"'. In the mySource, you can save the histroy value of sensorA and emit it together with sensorB value like {"a": v1, "b":v2}. And your SQL can deal with that input like `SELECT b where a = true`.
```
CREATE STREAM my_stream   
    (id int, name string, score float)
    WITH ( datasource = "topic/temperature", FORMAT = "json", TYPE = "mySource");
```

> Another idea, kuiper provide a common function to save certern data in context,
What is this common function look like and how to use in SQL? I think continuous table is a "common" artifact. If not urgent, please just wait for the table implementation. Thanks.

**Comment by ngjaying** [comment]
[Table](https://github.com/emqx/kuiper/blob/master/docs/en_US/sqls/tables.md) is supported in v1.2.0 so close this one. Please reopen it if you have more queries.
