### ISSUE TITLE
edgex sink documents are appreciated

### ISSUE THREAD

**Issue by cntwelve** [emqx/kuiper#756]
Hi, kuiper team:
I'm using kuiper with edgex, and I want to konw how to config a new edgex sink.
Thnaks a lot.

**Comment by ngjaying** [comment]
Hi, please check [edgex sink](https://github.com/emqx/kuiper/blob/master/docs/en_US/rules/sinks/edgex.md)

**Comment by cntwelve** [comment]
Hi, I do some configuration according to that document earlier, but cant get the right result. So where can I find a whole sample of config, both on an equipment and docker container. Step by Step is prefered:)

Thanks a lot.

**Comment by ngjaying** [comment]
Hi,
The sink config are written in the rule itself, there is no other configuration needed. In below rule definition, the edgex action will publish the result to the edgex message bus running in yourhost:5571. You'll need to start the edgex service in that address.
```
{
  "id": "rule1",
  "sql": "SELECT temperature * 3 AS t1, humidity FROM events",
  "actions": [
    {
      "edgex": {
        "protocol": "tcp",
        "host": "yourhost",
        "port": 5571,
        "topic": "application",
        "deviceName": "kuiper",
        "contentType": "application/json"
      }
    }
  ]
}
```

**Comment by cntwelve** [comment]
thanks for your reply!

I use docker enviroment from edgexfoundry, version h. I use kuiper-cli, and edgex web ui tool to configure the sink, all reply ok, but take no effect(no out put after i issue 'select * from application;').
Document metions: "Please notice that, if you're using the ZeorMQ message bus, the action will create a NEW EdgeX message bus (with the address where running Kuiper service), but not by leveraging the original message bus (normally it's the address & port exposed by application service). "
So which host should I use, host running edgex core, or core data, or app service, or kuiper?
And certern libs else are needed in order to run edgex sink?

**Comment by jinfahua** [comment]
As doc said, it's not possible to use another host for zeromq message bus. If you'd like to use the same message bus between application service, you can use mqtt message bus.

**Comment by cntwelve** [comment]
Well, I'll try mqtt solution.
Thanks.

**Comment by jinfahua** [comment]
Welcome.
