### ISSUE TITLE
Support the external function invocation

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#762]
Most of AI/ML algorithm are exposed with rest-api or rpc interface... Kuiper should have an approach that can be easily invoked.

 - [x] Discuss with 中科创达 & 江行智能 for AI support in Kuiper this week.
   - [x] Got the feedback from 中科创达 & 江行智能, and started to design. - 3/17
   - [x] Will go through the design with 中科创达 & 江行智能. - 3/17
   - [x] Reviewed with 中科创达 & 江行智能, and will schedule meeting with them after finish. - 3/30
   - [x] Under development 4/20

**Comment by ngjaying** [comment]
Supported in v1.2.0, close
