### ISSUE TITLE
Support EdgeX v2 message bus

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#763]
Hi Rocky and team,

The V2 API dependencies you need are ready for integration. 

Please update to using the following modules:

```
go-mod-messaging - v2.0.0-dev.10
No code change required beyond switching the V2 Module import paths
go-mod-core-contracts - v2.0.0-dev.73
```
Contains new Event/Reading DTOs & DeviceProfile Client for querying DeviceResources
 

Note that these modules are now V2 Go Modules (not be confused with our V2 API)

In your go.mod you will need to add the /v2 to these module urls.

```
github.com/edgexfoundry/go-mod-messaging/v2 v2.0.0-dev.10

github.com/edgexfoundry/go-mod-core-contracts/v2 v2.0.0-dev.73
```

Then all the import statements for these modules must have the /v2 in the path.

This is where it gets strange since our V2 API is under the v2 package in go-mod-core-contracts so the import for the dtos looks like this:

     "github.com/edgexfoundry/go-mod-core-contracts/v2/v2/dtos"

Note that before release, this double /v2/v2 will be eliminated once the old V1 code is removed and the v2 package eliminated.

We do need to discuss timing of releases so that you are using the final versions of these modules.

 

The new Event/Reading DTO changes from V1 are highlighted below:

```golang
type Event struct {
   common.Versionable
   Id                 string           
   DeviceName         string           
   ProfileName        string           
   SourceName         string           
   Origin             int64            
   Readings           []BaseReading    
   Tags               map[string]string
}
```
 

Note that Reading no longer has float encoding since floats are now always encode with e-notation

```golang
type BaseReading struct {
   Id            string
   Origin        int64 
   DeviceName    string
   ResourceName  string  
   ProfileName   string
   ValueType     string
   BinaryReading
   SimpleReading

}

type SimpleReading struct {
   Value string
}

type BinaryReading struct {
   BinaryValue []byte
   MediaType   string
}
```
 

The V1 ValueDescriptors have been removed for V2 API.

Do you need more than the ValueType for the reading?

If you need more details about the reading than the ValueType, then you can use the DeviceProfileClient found here:

https://github.com/edgexfoundry/go-mod-core-contracts/blob/v2.0.0-dev.73/v2/clients/http/deviceprofile.go#L33 passing the value of EDGEX__DEFAULT__SERVICESERVER as the base URL, which will change to http://edgex-core-metadata:48081

Then use the DeviceResourceByProfileNameAndResourceName API to retrieve the additional details for the reading.

This API caches the DeviceResources so subsequent calls for the same Profile/Resource do not result in REST calls, so you do not need to cache the resource yourself, just use the API each time.

Note this API returns a Response DTO which contains the DeviceResource DTO, which contains the follow ResourceProperties DTO containing the metadata that was previously in the ValueDescriptor.

 
```golang 
type ResourceProperties struct {
   ValueType    string
   ReadWrite    string
   Units        string
   Minimum      string
   Maximum      string

   DefaultValue string
   Mask         string

   Shift        string
   Scale        string
   Offset       string
   Base         string
   Assertion    string
   MediaType    string
}
```
 

Please let us know if you have any question or concerns.

 

Thanks!

   Lenny

**Comment by ngjaying** [comment]
Supported in 1.2.1 beta. Will open another issue to finalize it with the edgex ireland release. So close this one.
