### ISSUE TITLE
kuiper .deb support riscv 

### ISSUE THREAD

**Issue by kirana1996** [emqx/kuiper#788]
Hi, 
Issue : Not able install kuiper on target riscv(native build).
Reproduces:
*Git clone https://github.com/emqx/kuiper
*Cd kuiper
*make build_with_edgex

Build was successful.  We got  files " bin etc data log plugin " ,But Not able to do make install.  So can you help us copy all these file on target and make it works.

Note :  I copied all these file  on target following structure,
     kuiper_installed_dir
  bin
    server
    cli
  etc
    mqtt_source.yaml
    ...
  data
    ...
  plugins
    ...
  log
    ...

Not Working i was getting error:
kuiperd
time="2021-05-18 06:50:55" level=fatal msg="conf dir not found, please set KuiperBaseKey program environment variable correctly." file="common/util.go:149"

Thanks,

**Comment by ngjaying** [comment]
Hi @kirana1996 
The build target is in `${kuiper_path}/_build/kuiper-1.x.x-xxxxxx` instead of the kuiper install path. You should have all the needed directories there after a successful build. Please check.

**Comment by kirana1996** [comment]
All directories are present in ${kuiper_path}/_build/kuiper-1.x.x-xxxxxx. But thing is  i need copy those to on board and that should make it work in board.

**Comment by ngjaying** [comment]
@kirana1996 Could you try to set the environment variable `KuiperBaseKey` to point to your copied kuiper build path like *{kuiper_path}/_build/kuiper-1.x.x-xxxxxx*. And run again.

We also provide some prebuilt binaries including .deb in the release page of each kuiper version, like [1.1.2](https://github.com/emqx/kuiper/releases/tag/1.1.2) assets. You could check if there is installable binary for your environment.

**Comment by kirana1996** [comment]
@ngjaying I was run only command  "make build_with_edgex"  , Can tell how to set KuiperBaseKey.

**Comment by ngjaying** [comment]
> @ngjaying I was run only command "make build_with_edgex" , Can tell how to set KuiperBaseKey.

Kuiperd will find the dependant files in its directory by default. That can be overriden by setting system environment variable `KuiperBaseKey`. Just set it like a normal environment variable
```
export KuiperBaseKey=/var/kuiper/_build/kuiper-1.x.x-xxxxxx
```

**Comment by kirana1996** [comment]
@ngjaying , No i don´t want export environment. Just i want create .deb for _build. If install deb it should make it work. So please help support for that.
 If i install .deb all bin and lib are copying to /usr.

**Comment by ngjaying** [comment]
> @ngjaying , No i don´t want export environment. Just i want create .deb for _build. If install deb it should make it work. So please help support for that.
> If i install .deb all bin and lib are copying to /usr.

Are there any prebuilt .deb files in [this page](https://github.com/emqx/kuiper/releases/tag/1.1.2) working for you?

If you do need manual build, try to use **absolute** loadFileType. Modify the MakeFile of line 37&38 as below, the change is the build property main.LoadFileType is changing from relative to absolute.

```
GO111MODULE=on CGO_ENABLED=1 go build -ldflags="-s -w -X main.Version=$(VERSION) -X main.LoadFileType=absolute" -o kuiper xstream/cli/main.go
GO111MODULE=on CGO_ENABLED=1 go build -trimpath -ldflags="-s -w -X main.Version=$(VERSION) -X main.LoadFileType=absolute" -o kuiperd xstream/server/main.go
```

With this build property, kuiperd expectes the dependants in the below absolute path:

| Kuiper directory| Absolute Path|
| ----------- | ----------- |
| etc | /etc/kuiper |
| data| /var/lib/kuiper/data|
| log| /var/log/kuiper/|
| plugins|/var/lib/kuiper/plugins|

Copy contents in each directory to the corresponding absolute path.

**Comment by kirana1996** [comment]
@ngjaying, As per your guide changed all kuiper directories to absolute path, But not able start kuiperd server, you can see as bellow log..

# kuiperd
panic: (*logrus.Entry) 0x3f94246c40

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0x3f941553b0, 0x3f941a88d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x340
github.com/sirupsen/logrus.(*Entry).Log(0x3f94246000, 0x3f00000000, 0x3f94419e60, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xe0
github.com/sirupsen/logrus.(*Logger).Log(0x3f941553b0, 0x0, 0x3f94419e60, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x90
github.com/sirupsen/logrus.(*Logger).Panic(...)
	github.com/sirupsen/logrus@v1.4.2/logger.go:233
github.com/emqx/kuiper/xstream/server/server.StartUp(0x1142720, 0x11, 0x1138e08, 0x8)
	github.com/emqx/kuiper/xstream/server/server/server.go:55 +0x430
main.main()
	command-line-arguments/main.go:11 +0x54

**Comment by ngjaying** [comment]
Hi @kirana1996 
It seems you are building the master branch. Do you have path **/etc/kuiper/services and /etc/kuiper/services/schemas** created? That should be automatically created with make. What's in your log file /var/log/kuiper/stream.log.2021xxxx?

**Comment by kirana1996** [comment]
Hi @ngjaying , The files etc/service and servie/schemas schemas are created. but Nothing was in _build/log.

**Comment by ngjaying** [comment]
> Hi @ngjaying , The files etc/service and servie/schemas schemas are created. but Nothing was in _build/log.

I mean the absolute path of etc and log in that **mapping table** , not the relative path in your kuiper _build like **_build/log**. Please check again.

**Comment by ngjaying** [comment]
Hi @kirana1996 ,

I can reproduce the error of your last comment. I will create a PR soon. Thanks.

**Comment by ngjaying** [comment]
Hi @kirana1996 
A fix is merged to the master branch, you can try with it now. Thanks.

**Comment by ngjaying** [comment]
The fix is release in v1.2.0 so I will close this one. If you have more queries, just reopen it. Thanks.

**Comment by kirana1996** [comment]
@ngjaying, Thank you. Worked.

**Comment by ngjaying** [comment]
Thank you for verifying

**Comment by kirana1996** [comment]
hi @ngjaying,
I was trying to do ´absolute´ path build for the version 1.3.0, But not able get file in respective path. Can you please check.

**Comment by ngjaying** [comment]
Hi @kirana1996 , I just tried with master and I can start kuiperd with absolute. Could you please provide more detail? Did you get an error this time?

**Comment by kirana1996** [comment]
No..nothing was there in /var/lib/kuiper/data and service not found in /var/lib/kuiper/plugins

**Comment by ngjaying** [comment]
Those are supposed to be created by yourself if you are building from the code. Try to create the missing directory /var/lib/kuiper/plugins/sources

**Comment by kirana1996** [comment]
yes.. i missed..it is working now.
Thank you...

**Comment by ngjaying** [comment]
Great 👍

**Comment by kirana1996** [comment]
Hi, 
Trying for building docker image, but error was coming.

# make docker
docker buildx build --no-cache --platform=linux/riscv64 -t lfedge/ekuiper:1.3.0 -f deploy/docker/Dockerfile . --load
[+] Building 3.4s (6/13)                                                                                                                      
 => [internal] load build definition from Dockerfile                                                                                     0.1s
 => => transferring dockerfile: 32B                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                        0.2s
 => => transferring context: 2B                                                                                                          0.1s
 => ERROR [internal] load metadata for docker.io/library/golang:1.15.1                                                                   2.8s
 => [auth] sharing credentials for registry-1.docker.io                                                                                  0.0s
 => [internal] load build context                                                                                                        0.0s
 => ERROR [1/8] FROM docker.io/library/golang:1.15.1                                                                                     0.3s
 => => resolve docker.io/library/golang:1.15.1                                                                                           0.3s
------
 > [internal] load metadata for docker.io/library/golang:1.15.1:
------
------
 > [1/8] FROM docker.io/library/golang:1.15.1:
------
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: no match for platform in manifest sha256:bd7a499445abe17605c3c29ac4d924207c31f0274bcc011e933533ac603645e7: not found
make: *** [Makefile:113: docker] Error 1

Can help out solve this error...

**Comment by kirana1996** [comment]
Hi @ngjaying,
             We want kuiper 1.5.0 version there i checked absolute path was not working, So can you please check and update on this.

**Comment by kirana1996** [comment]
@ngjaying,
      I used master branch has 1.5.0 version and it was giving  /data not found while runing kuiperd.
kuiperd
panic: dir /data not found, please make sure it is created.

goroutine 1 [running]:
github.com/lf-edge/ekuiper/internal/server.StartUp(0x12a9efc, 0x5, 0x12aad10, 0x8)
	github.com/lf-edge/ekuiper/internal/server/server.go:52 +0xc08
main.main()
	command-line-arguments/main.go:25 +0x54

**Comment by kirana1996** [comment]
yea i have changed to absolute mode in makefile and also built but also i m facing the same above issue

**Comment by ngjaying** [comment]
There are several make target. If you are using `make`, make sure in the makefile `build_without_edgex` target is changed.

**Comment by kirana1996** [comment]
@ngjaying,
    We used make build_with_edgex command to build

**Comment by ngjaying** [comment]
Then you'll need to change the build_with_edgex target. What's your output log for make command?

**Comment by kirana1996** [comment]
@ngjaying ,
This is the my make log,
make
GO111MODULE=on CGO_ENABLED=1 go build -ldflags="-s -w -X main.Version=1.5.0-9-ga1cc932a -X main.LoadFileType=absolute" -o kuiper cmd/kuiper/main.go
GO111MODULE=on CGO_ENABLED=1 go build -trimpath -ldflags="-s -w -X main.Version=1.5.0-9-ga1cc932a -X main.LoadFileType=absolute" -o kuiperd cmd/kuiperd/main.go
Build successfully

**Comment by ngjaying** [comment]
The log seems right. But the binary you are running prints an error which will only happen in relative mode. Is it possible that you are not running this newly built kuiperd? Could you demonstrate in detail how do you run to recreate the problem?

**Comment by kirana1996** [comment]
@ngjaying,
       To reproduces:
          $ git clone https://github.com/lf-edge/ekuiper
          $ Vi Makefile -- changed to absolute path

Copied binaries as given:

Kuiper directory | Absolute Path
-- | --
etc | /etc/kuiper
data | /var/lib/kuiper/data
log | /var/log/kuiper/
plugins | /var/lib/kuiper/plugins

Error:
     /log , /data  not found at the root.. looking at root path( / ).

**Comment by ngjaying** [comment]
This works fine. Where is your binary kuiperd? What happens if you just run from its original place?

**Comment by kirana1996** [comment]
@ngjaying,
       kuiperd - /usr/bin
     If we run kuiperd, it gives error like bellow
         /log no such files or directtory and created log at / manually, then getting 
         /date no such files or directory 
So it's looking files at / not in the /var path.. Please check

**Comment by ngjaying** [comment]
@kirana1996 I can reproduce the exact same log by moving relative built kuiperd to /usr/bin. It is confusing to find the / path but it is as design for relative mode. 

It seems you are still using a relative built kuiperd. Can you check you creation date of your kuiperd file? Did you move the correct one?
