### ISSUE TITLE
two struct are not support in kuiper

### ISSUE THREAD

**Issue by bridgeren** [emqx/kuiper#792]
api ：`streams`
method: `post`
body： `{"sql":"create stream test(mid BIGINT,expire BIGINT,deviceId  STRING,param STRUCT(cmd STRING,deviceId STRING,data   STRUCT(elecQuantity STRING,humidity STRING,temp STRING))) WITH (DATASOURCE=\"topic/v1/HoldFastIot/service/data\", FORMAT=\"JSON\", KEY=\"id\")"}`

api response: `Stream test is created.`

but when i use  those ,  it  doesnot work 
api : `streams/test`
method: `Get`
api response: `json: error calling MarshalJSON for type xsql.StreamField: json: error calling MarshalJSON for type json.RawMessage: invalid character 'T' after object key:value pair
`

**Comment by ngjaying** [comment]
Hi @bridgeren There is a problem to print out such multipe level embeded struct. We will fix it. The stream is actually working, so you can go ahead and create rules against it.

**Comment by ngjaying** [comment]
Released in v1.2.0 so close. Thanks.
