### ISSUE TITLE
Failed to create rule from command line

### ISSUE THREAD

**Issue by cmf722123** [emqx/kuiper#801]
命令行创建规则失败
使用例子失败
执行：bin/kuiper create rule rule1 {"sql": "SELECT * from demo","actions": [{"log":  {}},{"mqtt":  {"server":"172.16.20.31:1883", "topic":"/tt1"}}]}
显示：Connecting to 127.0.0.1:20498...
Expect rule name and json.
But found 7 args:[rule1 {sql: SELECT * from demo,actions: [{log: {}},{mqtt: {server:172.16.20.31:1883, topic:/tt1}}]}].

**Comment by ngjaying** [comment]
@cmf722123 The rule json must be quoted by single quote or double quote when using cli.

```
bin/kuiper create rule rule1 '{"sql": "SELECT * from demo","actions": [{"log": {}},{"mqtt": {"server":"172.16.20.31:1883", "topic":"/tt1"}}]}'
```

**Comment by cmf722123** [comment]
thanks~
