### ISSUE TITLE
find some errs in docs

### ISSUE THREAD

**Issue by cmf722123** [emqx/kuiper#802]
File: [/docs/zh_CN/restapi/rules.md](https://docs.emqx.cn/kuiper/latest/restapi/rules.html)
some port is 9081 but docs write 8080
规则管理更新规则 删除规则 启动规则 停止规则 重启规则 获取规则状态
https://docs.emqx.cn/kuiper/latest/cli/rules.html
Command line tools 
The example of creating a rule is missing quotation marks when using JSON

**Comment by ngjaying** [comment]
Thanks for creating the issue, we will fix it.
