### ISSUE TITLE
Max rule support number

### ISSUE THREAD

**Issue by jinfahua** [emqx/kuiper#86]
Benchmark result for max rule support number for Kuiper.

**Comment by ngjaying** [comment]
Test Scenario:
2 Core 4G RAM
Rule{
Source: Mqtt
Sql: select temperature from source where temperature > 20
Sink: Log
}
90% data filtered

Rule | Data frequency | Duration | Result
-- | -- | -- | --
8000 | 1/rule/s | 5 minutes | RAM (3.45G） 90%, CPU 70%
8000 (disable sink cache) | 0.1/rule/s | 24 hours | RAM 89% -> 72%CPU 25%
