### ISSUE TITLE
Prometheus exporters( installing 2 prometheus exporters)

### ISSUE THREAD

**Issue by Daly123456** [emqx/kuiper#96]
i'am already using  prometheus blackbox exporter to alert expiry ssl 
can i install node-exporter too in the same prometheus server  ??

**Comment by jinfahua** [comment]
Not quite sure for your question... Kuiper metrics can be collected by Prometheus if you turn on the ``prometheus: true`` in ``etc/mqtt_source.yaml``.

**Comment by Daly123456** [comment]
i'am using prometheus :)

**Comment by jinfahua** [comment]
Close the issue.
